### ISSUE TITLE
thellier_gui.py crashes on 3.0 files with Key errors 

### ISSUE THREAD

**Issue by njarboe** [PmagPy/PmagPy#100]
While testing out the standalones on files upgraded by the beta site, demag_gui works fine on Ben-Yosif_2016 

[Ben-Yosef_2016_3.0.txt](https://github.com/PmagPy/PmagPy/files/714952/Ben-Yosef_2016_3.0.txt)

 but thellier_gui crashes with KeyError:'lat' on both windows and mac. Here is the mac error console (also some problem with getting the data model and method codes):
-I- Fetching output frame
-I- getting data model, please be patient
-W- Unable to fetch data model online
Trying to use cached data model instead
-I- running python script:
 thellier_gui.py -WD /Users/njarboe/Dropbox/MagIC/betaTesting/3.0DataFiles/Ben-Yosef
Data model set to 3.0
<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:661)> <class 'urllib2.URLError'>
-I- Couldn't connect to earthref.org, using cached method codes
-I- Importing controlled vocabularies from https://earthref.org
-I- Could not connect to earthref.org, using cached vocabularies instead
-I- overwriting /Users/njarboe/Dropbox/MagIC/betaTesting/3.0DataFiles/Ben-Yosef/specimens.bak
-I- overwriting /Users/njarboe/Dropbox/MagIC/betaTesting/3.0DataFiles/Ben-Yosef/samples.bak
-I- overwriting /Users/njarboe/Dropbox/MagIC/betaTesting/3.0DataFiles/Ben-Yosef/sites.bak
Traceback (most recent call last):
  File "/Users/njarboe/Desktop/PmagPy-Standalone-OSX-1.1.3/pmag_gui.app/Contents/Resources/pmag_gui.py", line 367, in on_run_thellier_gui
    thellier_gui.main(self.WD, standalone_app=False, parent=self, DM=self.data_model_num)
  File "programs/thellier_gui.pyc", line 7126, in main
  File "programs/thellier_gui.pyc", line 271, in __init__
  File "programs/thellier_gui.pyc", line 6598, in get_data_info
  File "pandas/core/frame.pyc", line 2059, in __getitem__
  File "pandas/core/frame.pyc", line 2066, in _getitem_column
  File "pandas/core/generic.pyc", line 1386, in _get_item_cache
  File "pandas/core/internals.pyc", line 3541, in get
  File "pandas/indexes/base.pyc", line 2136, in get_loc
  File "pandas/index.pyx", line 139, in pandas.index.IndexEngine.get_loc (pandas/index.c:4443)
  File "pandas/index.pyx", line 161, in pandas.index.IndexEngine.get_loc (pandas/index.c:4289)
  File "pandas/src/hashtable_class_helper.pxi", line 732, in pandas.hashtable.PyObjectHashTable.get_item (pandas/hashtable.c:13733)
  File "pandas/src/hashtable_class_helper.pxi", line 740, in pandas.hashtable.PyObjectHashTable.get_item (pandas/hashtable.c:13687)
KeyError: 'lat'

Also tried Killian_2016

[Killian_2016_3.0.txt](https://github.com/PmagPy/PmagPy/files/714954/Killian_2016_3.0.txt)

in demag_gui it looks fine but thellier_gui crashes with KeyError: 'aniso_s' in both standalones. Here is the console for that run:
-I- Fetching output frame
-I- getting data model, please be patient
-W- Unable to fetch data model online
Trying to use cached data model instead
-I- running python script:
 thellier_gui.py -WD /Users/njarboe/Dropbox/MagIC/betaTesting/3.0DataFiles/Killian
Data model set to 3.0
<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:661)> <class 'urllib2.URLError'>
-I- Couldn't connect to earthref.org, using cached method codes
-I- Importing controlled vocabularies from https://earthref.org
-I- Could not connect to earthref.org, using cached vocabularies instead
-I- overwriting /Users/njarboe/Dropbox/MagIC/betaTesting/3.0DataFiles/Killian/specimens.bak
-I- overwriting /Users/njarboe/Dropbox/MagIC/betaTesting/3.0DataFiles/Killian/samples.bak
-I- overwriting /Users/njarboe/Dropbox/MagIC/betaTesting/3.0DataFiles/Killian/sites.bak
sample already in specimens
Traceback (most recent call last):
  File "/Users/njarboe/Desktop/PmagPy-Standalone-OSX-1.1.3/pmag_gui.app/Contents/Resources/pmag_gui.py", line 367, in on_run_thellier_gui
    thellier_gui.main(self.WD, standalone_app=False, parent=self, DM=self.data_model_num)
  File "programs/thellier_gui.pyc", line 7126, in main
  File "programs/thellier_gui.pyc", line 272, in __init__
  File "programs/thellier_gui.pyc", line 5818, in get_data
  File "pandas/core/frame.pyc", line 2059, in __getitem__
  File "pandas/core/frame.pyc", line 2066, in _getitem_column
  File "pandas/core/generic.pyc", line 1386, in _get_item_cache
  File "pandas/core/internals.pyc", line 3541, in get
  File "pandas/indexes/base.pyc", line 2136, in get_loc
  File "pandas/index.pyx", line 139, in pandas.index.IndexEngine.get_loc (pandas/index.c:4443)
  File "pandas/index.pyx", line 161, in pandas.index.IndexEngine.get_loc (pandas/index.c:4289)
  File "pandas/src/hashtable_class_helper.pxi", line 732, in pandas.hashtable.PyObjectHashTable.get_item (pandas/hashtable.c:13733)
  File "pandas/src/hashtable_class_helper.pxi", line 740, in pandas.hashtable.PyObjectHashTable.get_item (pandas/hashtable.c:13687)
KeyError: 'aniso_s'

**Comment by moonshoes87** [comment]
Ok, the OSX Pmag GUI standalone doesn't yet expect 3.0.  There's a good oversight to catch now!  I will add that to the OSX standalone repo.

**Comment by moonshoes87** [comment]
I also found an issue because Thellier GUI is expecting 'int_abs' for specimens.  I changed that so that it doesn't choke, and will push that fix.  I will work on actually releasing a 3.0. Pmag GUI standalone.  In the meantime, @njarboe, you can use pmag_gui.py -DM 3 on the command line (you should pull and use the most recent version, not the last pip release)...

**Comment by njarboe** [comment]
Great. I can get that fix and try it out a bit more before you make the final version of the standalones and pip this evening. Then I can send out a notice to the people coming to PmagPy Day to install the latest version.

**Comment by moonshoes87** [comment]
Ok, I have now pushed a Thellier GUI fix to the main repo, and added a Pmag GUI 3 standalone to the OSX repo.  For the moment it is a separate program from Pmag GUI 2.  I didn't make a new standalone release yet, but you can download the updated stuff from the repo.

**Comment by njarboe** [comment]
Great, I'll give it a go.

**Comment by njarboe** [comment]
Hey Lori. I just pulled and the Killian file gives me the KeyError when trying to access the thellier_gui

Should this be working now? Maybe something wrong on my end. Here is the console output:
kamacite:programs njarboe$ ./pmag_gui.py -DM 3
-I- Importing Pmag GUI dependencies
-I- Starting Pmag GUI - please be patient
-I- Fetching output frame
-I- Read in any available data from working directory
-I- Importing controlled vocabularies from https://earthref.org
-W- No such file: /Users/njarboe/git/pmagpy/PmagPy/programs/measurements.txt
-W- No such file: /Users/njarboe/git/pmagpy/PmagPy/programs/specimens.txt
-W- No such file: /Users/njarboe/git/pmagpy/PmagPy/programs/samples.txt
-W- No such file: /Users/njarboe/git/pmagpy/PmagPy/programs/sites.txt
-W- No such file: /Users/njarboe/git/pmagpy/PmagPy/programs/locations.txt
-W- No such file: /Users/njarboe/git/pmagpy/PmagPy/programs/contribution.txt
-W- No such file: /Users/njarboe/git/pmagpy/PmagPy/programs/criteria.txt
-W- No such file: /Users/njarboe/git/pmagpy/PmagPy/programs/ages.txt
-W- No such file: /Users/njarboe/git/pmagpy/PmagPy/programs/images.txt
-I- Read in any available data from working directory
-I- Importing controlled vocabularies from https://earthref.org
-W- No such file: /Users/njarboe/Dropbox/MagIC/betaTesting/3.0DataFiles/Killian/images.txt
-I- running python script:
 thellier_gui.py -WD /Users/njarboe/Dropbox/MagIC/betaTesting/3.0DataFiles/Killian
Data model set to 3.0
-I- Importing controlled vocabularies from https://earthref.org
-I- Importing controlled vocabularies from https://earthref.org
-I- Importing controlled vocabularies from https://earthref.org
-I- overwriting /Users/njarboe/Dropbox/MagIC/betaTesting/3.0DataFiles/Killian/specimens.bak
-I- overwriting /Users/njarboe/Dropbox/MagIC/betaTesting/3.0DataFiles/Killian/samples.bak
-I- overwriting /Users/njarboe/Dropbox/MagIC/betaTesting/3.0DataFiles/Killian/sites.bak
sample already in specimens
Traceback (most recent call last):
  File "./pmag_gui.py", line 367, in on_run_thellier_gui
    thellier_gui.main(self.WD, standalone_app=False, parent=self, DM=self.data_model_num)
  File "/Users/njarboe/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/programs/thellier_gui.py", line 7140, in main
    frame = Arai_GUI(WD, parent, standalone=False, DM=DM)
  File "/Users/njarboe/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/programs/thellier_gui.py", line 282, in __init__
    self.Data,self.Data_hierarchy=self.get_data() # Get data from measurements and specimens or rmag_anisotropy (data model 2.5 if they exist.)
  File "/Users/njarboe/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/programs/thellier_gui.py", line 5836, in get_data
    anis_data=anis_data[anis_data['aniso_s'].notnull()] # get the ones with anisotropy tensors that aren't blank
  File "/Users/njarboe/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/pandas/core/frame.py", line 2057, in __getitem__
    return self._getitem_column(key)
  File "/Users/njarboe/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/pandas/core/frame.py", line 2064, in _getitem_column
    return self._get_item_cache(key)
  File "/Users/njarboe/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/pandas/core/generic.py", line 1386, in _get_item_cache
    values = self._data.get(item)
  File "/Users/njarboe/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/pandas/core/internals.py", line 3520, in get
    loc = self.items.get_loc(item)
  File "/Users/njarboe/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/pandas/indexes/base.py", line 2106, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas/index.pyx", line 139, in pandas.index.IndexEngine.get_loc (pandas/index.c:4160)
  File "pandas/index.pyx", line 161, in pandas.index.IndexEngine.get_loc (pandas/index.c:4024)
  File "pandas/src/hashtable_class_helper.pxi", line 732, in pandas.hashtable.PyObjectHashTable.get_item (pandas/hashtable.c:13161)
  File "pandas/src/hashtable_class_helper.pxi", line 740, in pandas.hashtable.PyObjectHashTable.get_item (pandas/hashtable.c:13115)
KeyError: 'aniso_s'

**Comment by moonshoes87** [comment]
Ok, I’ll try this out.

**Comment by moonshoes87** [comment]
You are using the pip version of pmagpy-cli.  You may want to use the command line instead (you will probably have to pip uninstall pmagpy-cli first).  I think this may have been changed.  

With the Killian data I end up with no data to look at in Thellier GUI, but it doesn't break in the way that your traceback shows.

**Comment by Swanson-Hysell** [comment]
This seems clear from Lori's last comment, but just to confirm, there should be no data to look at in Thellier GUI as that data file has remanence, but not paleointensity data.

**Comment by njarboe** [comment]
Ok. I was a bit worried about the pip version being run. I thought running ../pmag_gui.py in the program directory would bypass the possibility, but I guess that is not the case. I'll uninstall pip and find a file with paleointensity to test.

**Comment by moonshoes87** [comment]
If you run:

pip list

That should show you whether or not you have pmagpy or pmagpy-cli are still on the list of installed packages.

**Comment by njarboe** [comment]
Looks good now. Thanks for the help and info.

**Comment by njarboe** [comment]
Not sure if I should open a new issue for this error. I am testing out the Lawrence2009 data set downloaded from 2.5, upgraded to 3.0, and unpacked into the various tables (
[Lawrence2009.3.0.txt](https://github.com/PmagPy/PmagPy/files/717729/Lawrence2009.3.0.txt) ).

demag_gui loads but thellier_gui gives the following error:

njarboe$ pmag_gui.py -DM 3
-I- Importing Pmag GUI dependencies
-I- Starting Pmag GUI - please be patient
-I- Fetching output frame
-I- Read in any available data from working directory
-I- Getting method codes from earthref.org
-I- Importing controlled vocabularies from https://earthref.org
-I- Importing suggested vocabularies from https://earthref.org
-I- running python script:
 demag_gui.py -WD /Users/njarboe/Dropbox/MagIC/betaTesting/3.0DataFiles/Lawrence2009
-I- running python script:
 demag_gui.py -WD /Users/njarboe/Dropbox/MagIC/betaTesting/3.0DataFiles/Lawrence2009
-I- running python script:
 thellier_gui.py -WD /Users/njarboe/Dropbox/MagIC/betaTesting/3.0DataFiles/Lawrence2009
Data model set to 3
-I- maxdev  was added to criteria list and will be displayed on screen
-I- overwriting /Users/njarboe/Dropbox/MagIC/betaTesting/3.0DataFiles/Lawrence2009/specimens.bak
-I- overwriting /Users/njarboe/Dropbox/MagIC/betaTesting/3.0DataFiles/Lawrence2009/samples.bak
-I- overwriting /Users/njarboe/Dropbox/MagIC/betaTesting/3.0DataFiles/Lawrence2009/sites.bak
sample already in specimens
Traceback (most recent call last):
  File "/Users/njarboe/git/pmagpy/PmagPy/programs/pmag_gui.py", line 378, in on_run_thellier_gui
    thellier_gui.main(self.WD, standalone_app=False, parent=self, DM=self.data_model_num)
  File "/Users/njarboe/git/pmagpy/PmagPy/programs/thellier_gui.py", line 7271, in main
    frame = Arai_GUI(WD, parent, standalone=False, DM=DM)
  File "/Users/njarboe/git/pmagpy/PmagPy/programs/thellier_gui.py", line 289, in __init__
    self.Data,self.Data_hierarchy=self.get_data() # Get data from measurements and specimens or rmag_anisotropy (data model 2.5 if they exist.)
  File "/Users/njarboe/git/pmagpy/PmagPy/programs/thellier_gui.py", line 5963, in get_data
    if 'AniSpec' not in Data[s].keys(): Data[s]['AniSpec']={}  # make a blank
KeyError: 'mc121d1'

**Comment by moonshoes87** [comment]
I'm taking a look now, but this might be a problem for @ltauxe....

**Comment by moonshoes87** [comment]
I am making progress on this error.  The wrong intensity key is being used.  I believe I should be able to have a fix for this shortly.

**Comment by moonshoes87** [comment]
I fixed this and pushed changes (to both master and release).  Let me know if you find anything else!
