### ISSUE TITLE
New Builder KeyError when Importing Method Codes

### ISSUE THREAD

**Issue by Caoimhinmg** [PmagPy/PmagPy#140]
Not sure if you noticed this yet @moonshoes87, but it looks like there is a KeyError  in pmagpy.controlled_vocabularies3.get_meth_codes on the string "definition". Not sure what's up here and don't want to further break anything you're doing, but I can't instantiate a Contribution object which is making the writing to file and running the GUIs a bit challenging. Full error message bellow. 

```python
Traceback (most recent call last):
  File "../../../../programs/3_conversion_scripts/_2g_bin_magic.py", line 459, in <module>
    main(**kwargs)
  File "../../../../programs/3_conversion_scripts/_2g_bin_magic.py", line 370, in main
    con = nb.Contribution(output_dir_path,read_tables=[])
  File "/home/kevin/Code/Paleomag/PmagPy/pmagpy/new_builder.py", line 53, in __init__
    Contribution.vocab = cv.Vocabulary(dmodel=self.data_model)
  File "/home/kevin/Code/Paleomag/PmagPy/pmagpy/controlled_vocabularies3.py", line 37, in __init__
    self.get_all_vocabulary()
  File "/home/kevin/Code/Paleomag/PmagPy/pmagpy/controlled_vocabularies3.py", line 272, in get_all_vocabulary
    all_codes, code_types = self.get_meth_codes()
  File "/home/kevin/Code/Paleomag/PmagPy/pmagpy/controlled_vocabularies3.py", line 59, in get_meth_codes
    little_series = df['definition']
  File "/usr/local/lib/python2.7/dist-packages/pandas/core/frame.py", line 2059, in __getitem__
    return self._getitem_column(key)
  File "/usr/local/lib/python2.7/dist-packages/pandas/core/frame.py", line 2066, in _getitem_column
    return self._get_item_cache(key)
  File "/usr/local/lib/python2.7/dist-packages/pandas/core/generic.py", line 1386, in _get_item_cache
    values = self._data.get(item)
  File "/usr/local/lib/python2.7/dist-packages/pandas/core/internals.py", line 3543, in get
    loc = self.items.get_loc(item)
  File "/usr/local/lib/python2.7/dist-packages/pandas/indexes/base.py", line 2136, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas/index.pyx", line 132, in pandas.index.IndexEngine.get_loc (pandas/index.c:4433)
  File "pandas/index.pyx", line 154, in pandas.index.IndexEngine.get_loc (pandas/index.c:4279)
  File "pandas/src/hashtable_class_helper.pxi", line 732, in pandas.hashtable.PyObjectHashTable.get_item (pandas/hashtable.c:13742)
  File "pandas/src/hashtable_class_helper.pxi", line 740, in pandas.hashtable.PyObjectHashTable.get_item (pandas/hashtable.c:13696)
KeyError: 'definition'
```

**Comment by moonshoes87** [comment]
Checking this out.

**Comment by moonshoes87** [comment]
I'm switching back to using the cached version of method_codes.  There is something different with the formatting (maybe?) of the method codes json on earthref, so I'll have to figure this out in more detail a bit later.

**Comment by Caoimhinmg** [comment]
Well now that we've agreed on caching for the data model and vocabularies at the moment, and everything is working this is no longer an issue.
