### ISSUE TITLE
can't make upload file with 3_0 in pmag_gui

### ISSUE THREAD

**Issue by ltauxe** [PmagPy/PmagPy#150]
I get this error:  
-I- criteria written to  /Users/ltauxe/SpareRoom/papers/Judean_handles/Revision/3_0/upload.txt
-
-I- contribution file successfully read in
-I- Validating contribution
Traceback (most recent call last):
  File "/Users/ltauxe/Programs/PmagPy/GIT/PmagPy/programs/pmag_gui.py", line 538, in on_btn_upload
    contribution=self.contribution)
  File "/Users/ltauxe/Programs/PmagPy/GIT/PmagPy/pmagpy/ipmag.py", line 2833, in upload_magic3
    res = val_up3.validate_table(con, file_type, output_dir=dir_path)#, verbose=True)
  File "/Users/ltauxe/Programs/PmagPy/GIT/PmagPy/pmagpy/validate_upload3.py", line 485, in validate_table
    current_df = validate_df(current_df, current_dm, the_con)
  File "/Users/ltauxe/Programs/PmagPy/GIT/PmagPy/pmagpy/validate_upload3.py", line 274, in validate_df
    output = df[validation_name].apply(test_type, args=(value_type,))
  File "/Users/ltauxe/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/pandas/core/series.py", line 2294, in apply
    mapped = lib.map_infer(values, f, convert=convert_dtype)
  File "pandas/src/inference.pyx", line 1207, in pandas.lib.map_infer (pandas/lib.c:63843)
  File "/Users/ltauxe/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/pandas/core/series.py", line 2282, in <lambda>
    f = lambda x: func(x, *args, **kwds)
  File "/Users/ltauxe/Programs/PmagPy/GIT/PmagPy/pmagpy/validate_upload3.py", line 237, in test_type
    if str(int(value)) == value:
ValueError: invalid literal for int() with base 10: 'PRIVATE'

**Comment by moonshoes87** [comment]
This is fixed in 94ed654

@ltauxe, let me know if you have further problems here.
