### ISSUE TITLE
MagIC GUI Locations table KeyError

### ISSUE THREAD

**Issue by Caoimhinmg** [PmagPy/PmagPy#177]
Hey @moonshoes87, I've been debugging the new Python3 merged master branch and ran into a number of errors when running test_new_builder and test_magic_gui. I've solved most of these, but I can't seem to get rid of this error:

```python
-I- Trying to propagate ['lithologies', 'geologic_classes'] columns from sites table into locations table
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/pandas/indexes/base.py", line 2134, in get_loc
    return self._engine.get_loc(key)
  File "pandas/index.pyx", line 132, in pandas.index.IndexEngine.get_loc (pandas/index.c:4433)
  File "pandas/index.pyx", line 154, in pandas.index.IndexEngine.get_loc (pandas/index.c:4279)
  File "pandas/src/hashtable_class_helper.pxi", line 732, in pandas.hashtable.PyObjectHashTable.get_item (pandas/hashtable.c:13742)
  File "pandas/src/hashtable_class_helper.pxi", line 740, in pandas.hashtable.PyObjectHashTable.get_item (pandas/hashtable.c:13696)
KeyError: 'lithologies'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "programs/magic_gui.py", line 290, in make_grid_frame
    'locations', 'sites')
  File "/home/kevin/Code/Paleomag/PmagPy/pmagpy/new_builder.py", line 733, in propagate_cols_up
    res = grouped.apply(func, col)
  File "/usr/local/lib/python3.4/dist-packages/pandas/core/groupby.py", line 694, in apply
    return self._python_apply_general(f)
  File "/usr/local/lib/python3.4/dist-packages/pandas/core/groupby.py", line 698, in _python_apply_general
    self.axis)
  File "/usr/local/lib/python3.4/dist-packages/pandas/core/groupby.py", line 1611, in apply
    res = f(group)
  File "/usr/local/lib/python3.4/dist-packages/pandas/core/groupby.py", line 685, in f
    return func(g, *args, **kwargs)
  File "/home/kevin/Code/Paleomag/PmagPy/pmagpy/new_builder.py", line 726, in func
    lst = group[col_name][group[col_name].notnull()].unique()
  File "/usr/local/lib/python3.4/dist-packages/pandas/core/frame.py", line 2059, in __getitem__
    return self._getitem_column(key)
  File "/usr/local/lib/python3.4/dist-packages/pandas/core/frame.py", line 2066, in _getitem_column
    return self._get_item_cache(key)
  File "/usr/local/lib/python3.4/dist-packages/pandas/core/generic.py", line 1386, in _get_item_cache
    values = self._data.get(item)
  File "/usr/local/lib/python3.4/dist-packages/pandas/core/internals.py", line 3543, in get
    loc = self.items.get_loc(item)
  File "/usr/local/lib/python3.4/dist-packages/pandas/indexes/base.py", line 2136, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas/index.pyx", line 132, in pandas.index.IndexEngine.get_loc (pandas/index.c:4433)
  File "pandas/index.pyx", line 154, in pandas.index.IndexEngine.get_loc (pandas/index.c:4279)
  File "pandas/src/hashtable_class_helper.pxi", line 732, in pandas.hashtable.PyObjectHashTable.get_item (pandas/hashtable.c:13742)
  File "pandas/src/hashtable_class_helper.pxi", line 740, in pandas.hashtable.PyObjectHashTable.get_item (pandas/hashtable.c:13696)
KeyError: 'lithologies'
```

Any thoughts?

**Comment by moonshoes87** [comment]
I should be able to fix these tomorrow.  This is certainly related to changes I made recently and should be simple to handle.
