### ISSUE TITLE
Updated to Anaconda and updated with the master branch. "past" module is missing.

### ISSUE THREAD

**Issue by njarboe** [PmagPy/PmagPy#181]
Updated to Anaconda and updated with the master branch and now the past module is missing. Not sure if I missed installing something.

cit_magic.py -f bl6.sam -sn BL6009 -usr Hagstrum -loc 'Boring volcanic field' -A -mcd FS-FD:LT-AF-Z:SO-SM
Traceback (most recent call last):
  File "/Users/njarboe/git/pmagpy/PmagPy/programs/conversion_scripts/cit_magic.py", line 57, in <module>
    import pmagpy.pmag as pmag
  File "/Users/njarboe/git/pmagpy/PmagPy/pmagpy/__init__.py", line 22, in <module>
    from . import pmag
  File "/Users/njarboe/git/pmagpy/PmagPy/pmagpy/pmag.py", line 8, in <module>
    from past.utils import old_div
ModuleNotFoundError: No module named 'past'

or:

bgc_magic.py -h
Traceback (most recent call last):
  File "/Users/njarboe/git/pmagpy/PmagPy/programs/conversion_scripts/bgc_magic.py", line 50, in <module>
    from past.utils import old_div
ModuleNotFoundError: No module named 'past'

**Comment by Caoimhinmg** [comment]
There is a new dependency created because we decided that the command line functions and library modules that don't use elements of the wx library should at least for a short time support both Py2 and Py3 interpreters. So you should be able to fix this problem by `sudo conda install future` (I think, I haven't used conda for a bit). This should install both the future and past modules which are used to make cross compatible python2 and python3 code.

**Comment by njarboe** [comment]
That did the trick. Thanks for the quick response.
