### ISSUE TITLE
eqarea_magic.py

### ISSUE THREAD

**Issue by ltauxe** [PmagPy/PmagPy#206]
Downloading data from Swanson-Hysell's latest (doi: 10.1093/gji/ggv402) and unpacking with download_magic.py,  I get this error with eqarea_magic.py:  

hermione-pro-2:sh17 ltauxe$ eqarea.py -f tmp 
 S[a]ve to save plot, [q]uit without saving:  q
hermione-pro-2:sh17 ltauxe$ eqarea_magic.py -f pmag_sites.txt 
-I- Using cached 3.0 data model
-I- Using cached method codes
-I- Using cached vocabularies
-I- Importing suggested vocabularies from https://earthref.org
-I- Using cached suggested vocabularies
Traceback (most recent call last):
  File "/Users/ltauxe/anaconda/lib/python3.5/site-packages/pandas/core/indexes/base.py", line 2393, in get_loc
    return self._engine.get_loc(key)
  File "pandas/_libs/index.pyx", line 132, in pandas._libs.index.IndexEngine.get_loc (pandas/_libs/index.c:5239)
  File "pandas/_libs/index.pyx", line 154, in pandas._libs.index.IndexEngine.get_loc (pandas/_libs/index.c:5085)
  File "pandas/_libs/hashtable_class_helper.pxi", line 1207, in pandas._libs.hashtable.PyObjectHashTable.get_item (pandas/_libs/hashtable.c:20405)
  File "pandas/_libs/hashtable_class_helper.pxi", line 1215, in pandas._libs.hashtable.PyObjectHashTable.get_item (pandas/_libs/hashtable.c:20359)
KeyError: 'pmag_site'

and I shouldn't.  eqarea_magic.py should just read in the data and plot it.  and pmag_site is not a thing.  
where did this come from?

**Comment by ltauxe** [comment]
um.. my bad
