### ISSUE TITLE
thellier_gui

### ISSUE THREAD

**Issue by ltauxe** [PmagPy/PmagPy#233]
has this bug:  

Traceback (most recent call last):
  File "/Users/ltauxe/Programs/PmagPy/GIT/PmagPy/programs/thellier_gui.py", line 1629, in on_prev_button
    self.update_selection()
  File "/Users/ltauxe/Programs/PmagPy/GIT/PmagPy/programs/thellier_gui.py", line 1518, in update_selection
    self.update_GUI_with_new_interpretation()
  File "/Users/ltauxe/Programs/PmagPy/GIT/PmagPy/programs/thellier_gui.py", line 5840, in update_GUI_with_new_interpretation
    self.stat_windows[short_stat].SetBackGroundColour(wx.Green)
AttributeError: 'TextCtrl' object has no attribute 'SetBackGroundColour'

**Comment by ltauxe** [comment]
and thellier_gui fails to print the B_anc value and sometimes also the sample mean, even if there is a valid one.

**Comment by ltauxe** [comment]
here is the symptom and the upgraded data file:

![screen shot 2017-06-29 at 3 26 10 pm](https://user-images.githubusercontent.com/174861/27713202-4ee52770-5cdf-11e7-8276-4efc0be7fa59.png)
[Benaras.zip](https://github.com/PmagPy/PmagPy/files/1113687/Benaras.zip)

**Comment by ltauxe** [comment]
I found the bug - line 5840 had some typos (wx.Green) and SetBackGroundColour instead of wx.GREEN and SetBackgroundColour.
