### ISSUE TITLE
import scripts

### ISSUE THREAD

**Issue by ltauxe** [PmagPy/PmagPy#235]
some of these are seriously messed up - the variable command_line is not set and this causes the program to crash when the cooling rate option is called. this happens within pmag_gui and from the command line:  

sio_magic.py -F /Users/ltauxe/Dropbox/4Carlos/Archeomag3_0/Archarmenia.cool.magic -Fsp Archarmenia_specimens.txt -Fsa Archarmenia_samples.txt -Fsi Archarmenia_sites.txt -Flo Archarmenia_locations.txt -f /Users/ltauxe/Dropbox/4Carlos/Archeomag3_0/Archarmenia.cool -spc 1 -ncn 5  -LP T:CR 43.6,1.3 -loc Armenia -dc 40 0 -90
-I- Using less strict decoding, output may have formatting errors
Traceback (most recent call last):
  File "/Users/ltauxe/Programs/PmagPy/GIT/PmagPy/programs/conversion_scripts/sio_magic.py", line 762, in <module>
    main()
  File "/Users/ltauxe/Programs/PmagPy/GIT/PmagPy/programs/conversion_scripts/sio_magic.py", line 759, in main
    convert(**kwargs)
  File "/Users/ltauxe/Programs/PmagPy/GIT/PmagPy/programs/conversion_scripts/sio_magic.py", line 268, in convert
    if command_line:
NameError: name 'command_line' is not defined

**Comment by ltauxe** [comment]
found all the bugs in cooling rate import (there were many).  now it works.
