### ISSUE TITLE
thellier_gui is broken

### ISSUE THREAD

**Issue by ltauxe** [PmagPy/PmagPy#276]
objc[4635]: Class FIFinderSyncExtensionHost is implemented in both /System/Library/PrivateFrameworks/FinderKit.framework/Versions/A/FinderKit (0x7fffa0396a70) and /System/Library/PrivateFrameworks/FileProvider.framework/OverrideBundles/FinderSyncCollaborationFileProviderOverride.bundle/Contents/MacOS/FinderSyncCollaborationFileProviderOverride (0x1c1e1c0cd8). One of the two will be used. Which one is undefined.
-I- Read in any available data from working directory
-I- running python script:
 thellier_gui.py -WD /Users/ltauxe/Dropbox/4Christeanne/CoolingRatePaper/Aged_Thellier_III
-E- Can't read criteria file
Traceback (most recent call last):
  File "/Users/ltauxe/Programs/PmagPy/GIT/PmagPy/programs/pmag_gui.py", line 494, in on_run_thellier_gui
    evt_quit=ThellierGuiExitEvent)
  File "/Users/ltauxe/Programs/PmagPy/GIT/PmagPy/programs/thellier_gui.py", line 380, in __init__
    self.Data_info = self.get_data_info()  # get all ages, locations etc.
  File "/Users/ltauxe/Programs/PmagPy/GIT/PmagPy/programs/thellier_gui.py", line 7427, in get_data_info
    self.contribution.propagate_name_down('location', 'samples')
  File "/Users/ltauxe/Programs/PmagPy/GIT/PmagPy/pmagpy/new_builder.py", line 546, in propagate_name_down
    df = self.tables[df_name].df
KeyError: 'samples'

**Comment by ltauxe** [comment]
ummm.  just bad input file. nevermind
