### ISSUE TITLE
plot_magmap

### ISSUE THREAD

**Issue by ltauxe** [PmagPy/PmagPy#290]
breaks now.  If using matplotlib >2, it breaks because of some error in the way python3 does division.  but with matplotlib 1.5.3, it breaks for some other reason:  

/Users/ltauxe/anaconda/lib/python3.5/site-packages/mpl_toolkits/basemap/__init__.py:3644: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  xx = x[x.shape[0]/2,:]
Traceback (most recent call last):
  File "/Users/ltauxe/anaconda/lib/python3.5/site-packages/PIL/JpegImagePlugin.py", line 602, in _save
    rawmode = RAWMODE[im.mode]
KeyError: 'RGBA'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/ltauxe/Programs/PmagPy/GIT/PmagPy/programs/plot_magmap.py", line 123, in <module>
    main()
  File "/Users/ltauxe/Programs/PmagPy/GIT/PmagPy/programs/plot_magmap.py", line 119, in main
    plt.savefig('igrf'+d+'.'+fmt)
  File "/Users/ltauxe/anaconda/lib/python3.5/site-packages/matplotlib/pyplot.py", line 696, in savefig
    res = fig.savefig(*args, **kwargs)
  File "/Users/ltauxe/anaconda/lib/python3.5/site-packages/matplotlib/figure.py", line 1563, in savefig
    self.canvas.print_figure(*args, **kwargs)
  File "/Users/ltauxe/anaconda/lib/python3.5/site-packages/matplotlib/backend_bases.py", line 2232, in print_figure
    **kwargs)
  File "/Users/ltauxe/anaconda/lib/python3.5/site-packages/matplotlib/backends/backend_agg.py", line 583, in print_jpg
    return image.save(filename_or_obj, format='jpeg', **options)
  File "/Users/ltauxe/anaconda/lib/python3.5/site-packages/PIL/Image.py", line 1893, in save
    save_handler(self, fp, filename)
  File "/Users/ltauxe/anaconda/lib/python3.5/site-packages/PIL/JpegImagePlugin.py", line 604, in _save
    raise IOError("cannot write mode %s as JPEG" % im.mode)
OSError: cannot write mode RGBA as JPEG

I'm at a loss as to how to fix this....

**Comment by moonshoes87** [comment]
I'll work on this.  Can you give me an example of how plot_magmap should work?   We should put it into _PmagPy.ipynb so that it gets tested.

**Comment by ltauxe** [comment]
plot_magmap.py -el B  
should give a pretty plot of earth’s field intensity on  a Hammer projection
lisa

**Comment by moonshoes87** [comment]
For me, this command works correctly with:

1.  matplotlib 2.0/2.1 and basemap 1.0.7 with every format including jpeg

2. matplotlib 1.5 with every format other than jpeg.

3. matplotlib 1.5 with pillow downgraded to 4.1.1 with every format including jpeg

However, other plotting programs fail with matplotlib 1.5, unless this specific version of wxPython is downloaded:

    pip install -U --pre -f http://wxpython.org/Phoenix/snapshot-builds/ wxPython==4.0.0a1

So we do have a bit of a dependency mess. 

One thing at a time:

This is the jpeg issue: https://github.com/python-pillow/Pillow/issues/2609. 

Can you send me the error message you are seeing with plot_magmap using matplotlib 2.1?  For me, matplotlib 2.1 and everything else up to date works correctly.

**Comment by ltauxe** [comment]
pillow?

**Comment by moonshoes87** [comment]
Pillow is a hidden dependency that causes the jpeg error.

**Comment by ltauxe** [comment]
ah yes.  savefig doesn’t work with jpg anymore.  so we should remove that possibility. 
lisa

**Comment by ltauxe** [comment]
It works now - you just can't save in jpg format because of but in matplotlib.
