### ISSUE TITLE
thellier_gui problem when selecting interpretation bounds

### ISSUE THREAD

**Issue by moonshoes87** [PmagPy/PmagPy#291]
This error happens when trying to select bounds by double-clicking the list of measurements in this directory: data_files/Pmag_GUI/ThisProject/

    Traceback (most recent call last):
      File "/Users/nebula/Python/PmagPy/programs/thellier_gui.py", line 1182, in on_click_listctrl
        self.select_bounds_in_logger(index)
      File "/Users/nebula/Python/PmagPy/programs/thellier_gui.py", line 1214, in select_bounds_in_logger
        if index < tmax_index:
    TypeError: '<' not supported between instances of 'int' and 'str'

**Comment by moonshoes87** [comment]
This only happens when there isn't an interpretation yet, (in the docstring for select_bounds_in_logger:NOTE: Requires an interpretation to exist before it is called.              )

I am putting code so that when you first click, if there is no prior interpretation, it sets your initial click as tmin and the highest available temp as tmax.  

The whole implementation of this is still a bit buggy and awkward, because of indexing issues (if there are multiple steps with the same temperature, you can only choose the higher of the two).  Also, after a range has been selected, if you then click on a temperature in the middle of the range, it is ambiguous as to whether that click should replace tmin or tmax.
