### ISSUE TITLE
missing module named 'mpl_toolkits.basemap' when running polemap_magic.py using make_magic_plots

### ISSUE THREAD

**Issue by njarboe** [PmagPy/PmagPy#388]
When running make_magic_plots on this 3.0 file I get the error below. Is there another package I need to install?

Here is the magic text file.
[magic_contribution_12067.txt](https://github.com/PmagPy/PmagPy/files/2178720/magic_contribution_12067.txt)

working on:  Eastern Iceland
-I- writing sites records to /home/magic/batchPlots/12067/tmp_sites.txt
-I- 808 records written to sites file
-I- writing locations records to /home/magic/batchPlots/12067/tmp_locations.txt
-I- 5 records written to locations file
result file found sites.txt
number of datapoints:  808 Eastern Iceland
working on site directions
individual number of directions:  808
number of tilt corrected directions:  808
number of geographic  directions:  0
number of sample  directions:  0
number of no coordinates  directions:  0
eqarea_magic.py -f tmp_sites.txt -fsp tmp_specimens.txt -fsa tmp_samples.txt -flo tmp_locations.txt -sav -fmt png -crd t
1  saved in  LO:_Eastern Iceland_SI:_EA 10-_SA:__SP:__CO:_t_TY:_eqarea_.png
1  saved in  LO:_Eastern Iceland_SI:_EA 10-_SA:__SP:__CO:_t_TY:_eqarea_.png
working on VGP map
working on intensities
magic_select.py  -key int_abs 0. has -F tmp1.txt -f tmp_sites.txt
no data matched your criteria
grab_magic_key.py -f tmp1.txt -key int_abs | awk '{print $1*1e6}' >tmp2.txt
LO:__intensities_histogram:_.png
-W- No data found
histplot.py -b 1 -xlab 'Intensity (uT)' -sav -f tmp2.txt -F LO:__intensities_histogram:_.png
working on pole map
polemap_magic.py -sav -fmt png
Traceback (most recent call last):
  File "/home/magic/git/PmagPy/programs//polemap_magic.py", line 247, in <module>
    main()
  File "/home/magic/git/PmagPy/programs//polemap_magic.py", line 185, in main
    pmagplotlib.plotMAP(FIG['map'], [90.], [0.], Opts)
  File "/home/magic/git/PmagPy/pmagpy/pmagplotlib.py", line 2836, in plotMAP
    from mpl_toolkits.basemap import Basemap
ModuleNotFoundError: No module named 'mpl_toolkits.basemap'

**Comment by njarboe** [comment]
Here is the magic text file.
[magic_contribution_12067.txt](https://github.com/PmagPy/PmagPy/files/2178717/magic_contribution_12067.txt)

**Comment by njarboe** [comment]
Thanks. You said the cookbook was in flux, so I won't worry about why I did not have that already installed.
