### ISSUE TITLE
error in polemap_magic.py when running make_magic_plots - local variable 'files' referenced before assignment

### ISSUE THREAD

**Issue by njarboe** [PmagPy/PmagPy#389]
Running make_magic_plots with this file:
[magic_contribution_12066.txt](https://github.com/PmagPy/PmagPy/files/2178730/magic_contribution_12066.txt)

working on:  Laanila Dykes
-I- writing locations records to /home/magic/batchPlots/12066/tmp_locations.txt
-I- 1 records written to locations file
working on pole map
polemap_magic.py -sav -fmt png
Traceback (most recent call last):
  File "/home/magic/git/PmagPy/programs//polemap_magic.py", line 247, in <module>
    main()
  File "/home/magic/git/PmagPy/programs//polemap_magic.py", line 223, in main
    files[key] = 'LO:_' + locations+ '_POLE_map.' + fmt
UnboundLocalError: local variable 'files' referenced before assignment

**Comment by njarboe** [comment]
I had not updated in a few days. This error now gone. Will remember to do that first next time. Thanks for taking a look.
