### ISSUE TITLE
error being thrown for get_temp_indices in demag_gui.py

### ISSUE THREAD

**Issue by Swanson-Hysell** [PmagPy/PmagPy#44]
This error was thrown when switching between coordinate systems and is being thrown in other use cases as well.

```
Traceback (most recent call last):
  File "/Users/Laurentia/PmagPy/demag_gui.py", line 1548, in onSelect_coordinates
    fit.put(specimen,self.COORDINATE_SYSTEM,self.get_PCA_parameters(specimen,fit.tmin,fit.tmax,self.COORDINATE_SYSTEM,fit.PCA_type))
  File "/Users/Laurentia/PmagPy/demag_gui.py", line 1942, in get_PCA_parameters
    beg_pca,end_pca = self.get_temp_indices(None, tmin, tmax, specimen)
  File "/Users/Laurentia/PmagPy/demag_gui.py", line 4730, in get_temp_indices
    if tmin in self.Data[specimen]['zijdblock_steps']:
KeyError: 'PI47-3'
```

**Comment by Caoimhinmg** [comment]
Put in error messages for this occurrence and generally bolstered the ability of the function that figures out the index of measurement steps so that it can handle what were illegal inputs without completely crashing.
