### ISSUE TITLE
cont_rot.py example fails with cartopy

### ISSUE THREAD

**Issue by moonshoes87** [PmagPy/PmagPy#448]
cont\_rot.py is not working correctly with cartopy.

**What command was run:**

`cont_rot.py -con af:sam -prj ortho -eye -20 0 -sym k-  1 -age 180 -res l  -fmt png`

**What happened:**

    Traceback (most recent call last):
      File "/Users/nebula/anaconda3/lib/python3.6/tkinter/__init__.py", line 1702, in __call__
    return self.func(*args)
      File "/Users/nebula/anaconda3/lib/python3.6/tkinter/__init__.py", line 746, in callit
    func(*args)
      File "/Users/nebula/anaconda3/lib/python3.6/site-packages/matplotlib/backends/_backend_tk.py", line 310, in idle_draw
    self.draw()
      File "/Users/nebula/anaconda3/lib/python3.6/site-packages/matplotlib/backends/backend_tkagg.py", line 12, in draw
    super(FigureCanvasTkAgg, self).draw()
      File "/Users/nebula/anaconda3/lib/python3.6/site-packages/matplotlib/backends/backend_agg.py", line 437, in draw
    self.figure.draw(self.renderer)
      File "/Users/nebula/anaconda3/lib/python3.6/site-packages/matplotlib/artist.py", line 55, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
      File "/Users/nebula/anaconda3/lib/python3.6/site-packages/matplotlib/figure.py", line 1493, in draw
    renderer, self, artists, self.suppressComposite)
      File "/Users/nebula/anaconda3/lib/python3.6/site-packages/matplotlib/image.py", line 141, in _draw_list_compositing_images
    a.draw(renderer)
      File "/Users/nebula/anaconda3/lib/python3.6/site-packages/matplotlib/artist.py", line 55, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
      File "/Users/nebula/anaconda3/lib/python3.6/site-packages/cartopy/mpl/geoaxes.py", line 385, in draw
    inframe=inframe)
      File "/Users/nebula/anaconda3/lib/python3.6/site-packages/matplotlib/artist.py", line 55, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
      File "/Users/nebula/anaconda3/lib/python3.6/site-packages/matplotlib/axes/_base.py", line 2635, in draw
    mimage._draw_list_compositing_images(renderer, self, artists)
      File "/Users/nebula/anaconda3/lib/python3.6/site-packages/matplotlib/image.py", line 141, in _ draw_list_compositing_images
    a.draw(renderer)
      File "/Users/nebula/anaconda3/lib/python3.6/site-packages/matplotlib/artist.py", line 55, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
      File "/Users/nebula/anaconda3/lib/python3.6/site-packages/matplotlib/lines.py", line 756, in draw
    tpath, affine = (self._get_transformed_path()
      File "/Users/nebula/anaconda3/lib/python3.6/site-packages/matplotlib/transforms.py", line 2848, in get_transformed_path_and_affine
    self._revalidate()
      File "/Users/nebula/anaconda3/lib/python3.6/site-packages/matplotlib/transforms.py", line 2825, in _revalidate
    self._transform.transform_non_affine(self._path.vertices),
      File "/Users/nebula/anaconda3/lib/python3.6/site-packages/matplotlib/transforms.py", line 2482, in transform_non_affine
    return self._a.transform_non_affine(points)
      File "/Users/nebula/anaconda3/lib/python3.6/site-packages/cartopy/mpl/geoaxes.py", line 137, in transform_non_affine
    xy[:, 0], xy[:, 1])[:, 0:2]
      File "lib/cartopy/_crs.pyx", line 381, in cartopy._crs.CRS.transform_points
    IndexError: Out of bounds on buffer access (axis 0)

**What I expected to happen:**

The figure should have been drawn with no error.

**Screenshot(s):**

The image is (at least) partially drawn:

<img width="623" alt="screen shot 2018-10-08 at 12 51 14 pm" src="https://user-images.githubusercontent.com/1836578/46630400-f5d6df00-caf8-11e8-8f3c-67f0dad79f4b.png">

@ltauxe, what do you want to do about this?

**Comment by moonshoes87** [comment]
I'm going to leave this open since it would be nice to update it eventually.

**Comment by ltauxe** [comment]
nah - if someone wants to do it, they can do it through the PmagPy notebook way.  it’s ok
lisa
