### ISSUE TITLE
Tauxe 2004 still not quite right

### ISSUE THREAD

**Issue by moonshoes87** [PmagPy/PmagPy#458]
@ltauxe, it looks like this contribution is still not working correctly:

https://earthref.org/MagIC/16520

I get this error when I try to open Thellier GUI:

```
Traceback (most recent call last):
  File "/Users/nebula/Python/PmagPy/programs/pmag_gui.py", line 475, in on_btn_thellier_gui
    evt_quit=ThellierGuiExitEvent)
  File "/Users/nebula/Python/PmagPy/programs/thellier_gui.py", line 400, in __init__
    self.Data, self.Data_hierarchy = self.get_data()
  File "/Users/nebula/Python/PmagPy/programs/thellier_gui.py", line 7196, in get_data
    araiblock, field = self.sortarai(datablock, s, 0)
  File "/Users/nebula/Python/PmagPy/programs/thellier_gui.py", line 8074, in sortarai
    idec = float(irec["measurement_dec"])
TypeError: float() argument must be a string or a number, not 'NoneType'
```

I believe I fixed the root cause of why some 0s may have been replaced with np.nan/None (it was an issue of whether or not to treat 0 as null).  I didn't fully implement that fix until October 19 at 5 pm, so it looks like you might not have had the patch at the time when you re-uploaded the dataset.  Sorry :\

If you try again with the patch and it *still* doesn't work, then we'll know I missed something in my fix.

**Comment by moonshoes87** [comment]
@ltauxe, I've fixed this. You should be able to upload the fixed version now.
