### ISSUE TITLE
Demag GUI VGP viewer Mercator/Mollweide projections

### ISSUE THREAD

**Issue by moonshoes87** [PmagPy/PmagPy#463]
Some projections don't work well with the Demag GUI VGP viewer.  The stereographic projections work, but Mercator and Mollweide don't look very good.

See the McMurdo data:

<img width="1228" alt="screen shot 2018-10-25 at 3 15 38 pm" src="https://user-images.githubusercontent.com/1836578/47533512-da920080-d868-11e8-9767-d6cb24242c7b.png">
<img width="1228" alt="screen shot 2018-10-25 at 3 16 05 pm" src="https://user-images.githubusercontent.com/1836578/47533524-e978b300-d868-11e8-8307-27a24f377940.png">

@Swanson-Hysell or @ltauxe, any ideas about this?

**Comment by Caoimhinmg** [comment]
Oh wow, that's new, and for some reason it doesn't do that on my machine. Regardless I dug into it a bit and it looks like it may have to do with this [cartopy issue](https://github.com/SciTools/cartopy/pull/324) which was linked to by [this one](https://github.com/SciTools/cartopy/issues/624). Our best bet may be to try to verify it is a cartopy bug and that all those that are experiencing the bug have the newest version of cartopy. Then if the problem persists reopen the issue and try to work with them on a solution. In the mean time the north polar stereographic is the most common projection for this kind of analysis anyway.

**Comment by moonshoes87** [comment]
Here is my cartopy version:

    cartopy                   0.16.0           py36h9263bd1_0 

Have you tried upgrading your cartopy?  I'll also try downgrading and see what happens.

Alternatively, we could wait on this a while.  Looks like 0.17 is expected in early November, so several fixes will be added (including some of our issues).

**Comment by moonshoes87** [comment]
Installed the latest (dev) version of cartopy from Github, in which case Mercator works but Mollweide gives a lengthy error:

```
Traceback (most recent call last):
  File "/Users/nebula/Python/PmagPy/dialogs/demag_dialogs.py", line 205, in on_proj_box
    self.plot()
  File "/Users/nebula/Python/PmagPy/dialogs/demag_dialogs.py", line 282, in plot
    dp["vgp_dp"])*111.32, float(dp["vgp_dm"])*111.32, azi, color=dp['color'])
  File "/Users/nebula/Python/PmagPy/pmagpy/ipmag.py", line 2601, in ellipse
    map_axis.plot(X, Y, transform=ccrs.Geodetic(),**kwargs)
  File "/Users/nebula/anaconda3/lib/python3.6/site-packages/matplotlib/__init__.py", line 1867, in inner
    return func(ax, *args, **kwargs)
  File "/Users/nebula/anaconda3/lib/python3.6/site-packages/matplotlib/axes/_axes.py", line 1529, in plot
    self.add_line(line)
  File "/Users/nebula/anaconda3/lib/python3.6/site-packages/matplotlib/axes/_base.py", line 1960, in add_line
    self._update_line_limits(line)
  File "/Users/nebula/anaconda3/lib/python3.6/site-packages/matplotlib/axes/_base.py", line 2001, in _update_line_limits
    na_path, _ = line_trans_path.get_transformed_path_and_affine()
  File "/Users/nebula/anaconda3/lib/python3.6/site-packages/matplotlib/transforms.py", line 2848, in get_transformed_path_and_affine
    self._revalidate()
  File "/Users/nebula/anaconda3/lib/python3.6/site-packages/matplotlib/transforms.py", line 2822, in _revalidate
    self._transform.transform_path_non_affine(self._path)
  File "/Users/nebula/anaconda3/lib/python3.6/site-packages/matplotlib/transforms.py", line 2492, in transform_path_non_affine
    return self._a.transform_path_non_affine(path)
  File "/Users/nebula/anaconda3/lib/python3.6/site-packages/cartopy/mpl/geoaxes.py", line 192, in transform_path_non_affine
    geom, self.source_projection)
  File "/Users/nebula/anaconda3/lib/python3.6/site-packages/cartopy/crs.py", line 193, in project_geometry
    return getattr(self, method_name)(geometry, src_crs)
  File "/Users/nebula/anaconda3/lib/python3.6/site-packages/cartopy/crs.py", line 348, in _project_polygon
    return self._rings_to_multi_polygon(rings, is_ccw)
  File "/Users/nebula/anaconda3/lib/python3.6/site-packages/cartopy/crs.py", line 598, in _rings_to_multi_polygon
    multi_poly = sgeom.MultiPolygon(polygon_bits)
  File "/Users/nebula/anaconda3/lib/python3.6/site-packages/shapely/geometry/multipolygon.py", line 62, in __init__
    self._geom, self._ndim = geos_multipolygon_from_polygons(polygons)
  File "/Users/nebula/anaconda3/lib/python3.6/site-packages/shapely/geometry/multipolygon.py", line 185, in geos_multipolygon_from_polygons
    geom, ndims = polygon.geos_polygon_from_py(shell, holes)
  File "/Users/nebula/anaconda3/lib/python3.6/site-packages/shapely/geometry/polygon.py", line 494, in geos_polygon_from_py
    ret = geos_linearring_from_py(shell)
  File "shapely/speedups/_speedups.pyx", line 239, in shapely.speedups._speedups.geos_linearring_from_py
ValueError: A LinearRing must have at least 3 coordinate tuples
```

**Comment by lfairchild** [comment]
I was having these same issues earlier. I made a few tweaks that were merged a few days ago (pull request #462) that seem to have improved these display problems on my end (with the 0.16.0 release of cartopy). Let me know if/when either of you have a chance to test it out and whether you're still seeing these problems on your end.

**Comment by moonshoes87** [comment]
@lfairchild, it looks like an error is still occurring with the Mollweide projection (using cartopy 0.16.0 and the latest PmagPy on master).  All of the other projections work great, though.

**Comment by lfairchild** [comment]
I initially had trouble reproducing that error with other data but then saw the same thing when opening up the McMurdo data files. The code appears to be getting hung up while drawing the ellipse for only one site, mc43. Upon quick inspection of the ellipse coordinates (output by `ipmag.ellipse`), the mc43 data appear to be irregular/non-elliptical. I'm not sure why this is the case for this particular site, but I'm also still not sure why cartopy isn't able to plot the coordinates regardless of what shape they make...

Since this appears to be an uncommon bug (all other McMurdo sites plot successfully once this error is caught), I went ahead and added some code to `ipmag.ellipse` that handles this exception and issues a warning, e.g.
```
-E- An error occurred while plotting VGP data for mc43 in the Mollweide projection.
```
While the underlying issue with the shapely `ValueError` is still a mystery, perhaps this could an adequate work-around in the meantime?

**Comment by moonshoes87** [comment]
This seems great!
