### ISSUE TITLE
Latest plot server run log with errors

### ISSUE THREAD

**Issue by njarboe** [PmagPy/PmagPy#482]
@moonshoes87, 
Here is the latest log from the plot server. Below is the first error message in the file. Searching on "Traceback" works well to find the others in the log. I imagine you won't get to these until after AGU but, as we discussed, implementing plots on the website should not be an issue as is. The plots will just be missing. 

Plotting log:https://pmagpy.earthref.org/plots/batchLog.txt

/home/magic/contributions/batchPlots/12578
working on:  'contribution'
1  records written to file  ./contribution.txt
contribution  data put in  ./contribution.txt
working on:  'locations'
2  records written to file  ./locations.txt
locations  data put in  ./locations.txt
working on:  'ages'
2  records written to file  ./ages.txt
ages  data put in  ./ages.txt
-I- Using online data model
Traceback (most recent call last):
  File "/home/magic/git/PmagPy/programs//polemap_magic.py", line 348, in <module>
    main()
  File "/home/magic/git/PmagPy/programs//polemap_magic.py", line 225, in main
    pmagplotlib.plot_map(FIG['map'], pole_lats, pole_lons, Opts)
  File "/home/magic/git/PmagPy/pmagpy/pmagplotlib.py", line 3353, in plot_map
    transform=ccrs.Geodetic(), edgecolors=Opts['edgecolor'])
  File "/home/magic/anaconda3/lib/python3.6/site-packages/cartopy/mpl/geoaxes.py", line 1429, in scatter
    result = matplotlib.axes.Axes.scatter(self, *args, **kwargs)
  File "/home/magic/anaconda3/lib/python3.6/site-packages/matplotlib/__init__.py", line 1855, in inner
    return func(ax, *args, **kwargs)
  File "/home/magic/anaconda3/lib/python3.6/site-packages/matplotlib/axes/_axes.py", line 4349, in scatter
    self.add_collection(collection)
  File "/home/magic/anaconda3/lib/python3.6/site-packages/matplotlib/axes/_base.py", line 1897, in add_collection
    self.update_datalim(collection.get_datalim(self.transData))
  File "/home/magic/anaconda3/lib/python3.6/site-packages/matplotlib/collections.py", line 199, in get_datalim
    offsets = transOffset.transform_non_affine(offsets)
  File "/home/magic/anaconda3/lib/python3.6/site-packages/matplotlib/transforms.py", line 2489, in transform_non_affine
    return self._a.transform_non_affine(points)
  File "/home/magic/anaconda3/lib/python3.6/site-packages/cartopy/mpl/geoaxes.py", line 137, in transform_non_affine
    xy[:, 0], xy[:, 1])[:, 0:2]
  File "lib/cartopy/_crs.pyx", line 381, in cartopy._crs.CRS.transform_points
IndexError: Out of bounds on buffer access (axis 0)

**Comment by moonshoes87** [comment]
Another new error:

```
Dirctory is 13238
/home/magic/contributions/batchPlots/13238
working on:  'contribution'
1  records written to file  ./contribution.txt
contribution  data put in  ./contribution.txt
working on:  'locations'
3  records written to file  ./locations.txt
locations  data put in  ./locations.txt
working on:  'sites'
3  records written to file  ./sites.txt
sites  data put in  ./sites.txt
working on:  'samples'
48  records written to file  ./samples.txt
samples  data put in  ./samples.txt
working on:  'specimens'
212  records written to file  ./specimens.txt
specimens  data put in  ./specimens.txt
working on:  'measurements'
1350  records written to file  ./measurements.txt
measurements  data put in  ./measurements.txt
working on:  'ages'
3  records written to file  ./ages.txt
ages  data put in  ./ages.txt
-I- Using online data model
Traceback (most recent call last):
  File "/home/magic/git/PmagPy/programs//zeq_magic.py", line 586, in <module>
    main()
  File "/home/magic/git/PmagPy/programs//zeq_magic.py", line 369, in main
    pmagplotlib.plot_zed(ZED, datablock, angle, title, units)
  File "/home/magic/git/PmagPy/pmagpy/pmagplotlib.py", line 915, in plot_zed
    plot_mag(ZED['demag'], datablock, s, 1, units, norm)
  File "/home/magic/git/PmagPy/pmagpy/pmagplotlib.py", line 793, in plot_mag
    M.append(old_div(rec[3], Ints[-1]))
  File "/home/magic/anaconda3/lib/python3.6/site-packages/past/utils/__init__.py", line 95, in old_div
    return a / b
ZeroDivisionError: float division by zero
```

**Comment by moonshoes87** [comment]
Another:

```
/home/magic/contributions/batchPlots/13357
working on:  'contribution'
1  records written to file  ./contribution.txt
contribution  data put in  ./contribution.txt
working on:  'locations'
1  records written to file  ./locations.txt
locations  data put in  ./locations.txt
working on:  'sites'
16  records written to file  ./sites.txt
sites  data put in  ./sites.txt
working on:  'specimens'
15  records written to file  ./specimens.txt
specimens  data put in  ./specimens.txt
working on:  'ages'
16  records written to file  ./ages.txt
ages  data put in  ./ages.txt
-I- Using online data model
Traceback (most recent call last):
  File "/home/magic/anaconda3/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 3064, in get_loc
    return self._engine.get_loc(key)
  File "pandas/_libs/index.pyx", line 140, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 162, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1492, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1500, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'specimen'
```

**Comment by moonshoes87** [comment]
Another:
```
Dirctory is 13631
/home/magic/contributions/batchPlots/13631
working on:  'contribution'
1  records written to file  ./contribution.txt
contribution  data put in  ./contribution.txt
working on:  'locations'
1  records written to file  ./locations.txt
locations  data put in  ./locations.txt
working on:  'sites'
1  records written to file  ./sites.txt
sites  data put in  ./sites.txt
working on:  'samples'
9  records written to file  ./samples.txt
samples  data put in  ./samples.txt
working on:  'specimens'
9  records written to file  ./specimens.txt
specimens  data put in  ./specimens.txt
working on:  'measurements'
91  records written to file  ./measurements.txt
measurements  data put in  ./measurements.txt
working on:  'ages'
1  records written to file  ./ages.txt
ages  data put in  ./ages.txt
-I- Using online data model
1  saved in  LO:_DiscoverySite_SI:_JH5O_SA:_5s1-f1_SP:_5s1-f1_TY:_eqarea_.png
2  saved in  LO:_DiscoverySite_SI:_JH5O_SA:_5s1-f1_SP:_5s1-f1_TY:_zijd_.png
3  saved in  LO:_DiscoverySite_SI:_JH5O_SA:_5s1-f1_SP:_5s1-f1_TY:_demag_.png
Traceback (most recent call last):
  File "/home/magic/git/PmagPy/programs//zeq_magic.py", line 586, in <module>
    main()
  File "/home/magic/git/PmagPy/programs//zeq_magic.py", line 491, in main
    mpars['specimen_dang'])
KeyError: 'specimen_dang'
```

**Comment by moonshoes87** [comment]
```
/home/magic/contributions/batchPlots/13797
Traceback (most recent call last):
  File "/home/magic/git/PmagPy/programs//vgpmap_magic.py", line 237, in <module>
    main()
  File "/home/magic/git/PmagPy/programs//vgpmap_magic.py", line 162, in main
    isign = abs(lats[-1]) / lats[-1]
ZeroDivisionError: float division by zero
-I- Using online data model
```

**Comment by moonshoes87** [comment]
A list of additional contributions with (apparently unique) errors:

/home/magic/contributions/batchPlots/14019
/home/magic/contributions/batchPlots/14254
/home/magic/contributions/batchPlots/14290
/home/magic/contributions/batchPlots/14575
/home/magic/contributions/batchPlots/14736
/home/magic/contributions/batchPlots/15417
/home/magic/contributions/batchPlots/16302
/home/magic/contributions/batchPlots/16320
/home/magic/contributions/batchPlots/16376
/home/magic/contributions/batchPlots/16410

**Comment by njarboe** [comment]
@moonshoes87 
I wasn't sure how best to report the dozen or more errors in the log but listing each one in its own comment is a good idea I'll follow in the future. I'm sure some of these errors are due to bad data that would now not pass our validation and never be in the database. In those cases it is good if an error message get thrown or even a crash, instead of the error just getting ignored. I'm not sure how you are setting that up exactly in make_magic_plots and the other programs. Are you writing messages to standard err? 

Thanks for going through these. If you find ones where the data is bad, would you let me know. I can make an issue in MagIC to list them so we can fix them up in the future.

**Comment by moonshoes87** [comment]
I'm giving each individual comment a thumbs up when it's solved.

**Comment by moonshoes87** [comment]
@njarboe, I'll let you know if there is obviously bad data.  

We still need to deal with bad data gracefully though, right?  Or do we expect to fix all data to pass validations?

**Comment by moonshoes87** [comment]
And yes, I do write out my custom error messages to sys.stderr.

**Comment by njarboe** [comment]
@moonshoes87 
Hopefully in the future all data will pass validations. Going back and fixing everything will take some time and really more people working for MagIC. In the near future (in a few weeks) new data will be fully validated and any data errors that get by validation will be cause to fix up the validation code.

**Comment by njarboe** [comment]
@moonshoes87 
I don't think we will be rerunning make_magic_plots on every contribution very often. Only when a new plot type is added. So if a few have really corrupt data, we can just know that is the case and ignore the errors. Once the major plot debugging is done, the plot server will just take new contribution data and create the plots for that.

**Comment by moonshoes87** [comment]
I'm adding contributions with bad data in this issue:  https://github.com/earthref/MagIC/issues/391

**Comment by njarboe** [comment]
Ok. Re-running now.
