### ISSUE TITLE
thellier_magic.py produces "posx posy should be finite values" error

### ISSUE THREAD

**Issue by moonshoes87** [PmagPy/PmagPy#486]
**What command was run:**

```
thellier_magic.py -f tmp_measurements.txt -fsp tmp_specimens.txt -sav -fmt png
```

**What happened:**

`posx posy should be finite values` error happens for 4 specimens.

**Data file(s):**

[magic_contribution_16302.txt](https://github.com/PmagPy/PmagPy/files/2661075/magic_contribution_16302.txt)

**Comment by moonshoes87** [comment]
I'm wondering if this is related to https://github.com/PmagPy/PmagPy/issues/509

**Comment by moonshoes87** [comment]
I'm now looking at this contribution again, and finding a different (related?) error.  

Running this command in the directory:
`thellier_magic.py -sav`

gives me this error:

```
Traceback (most recent call last):
  File "/Users/nebula/Python/PmagPy/programs/thellier_magic.py", line 108, in <module>
    main()
  File "/Users/nebula/Python/PmagPy/programs/thellier_magic.py", line 99, in main
    spec, n_specs, save_plots, fmt, interactive)
  File "/Users/nebula/Python/PmagPy/pmagpy/ipmag.py", line 10247, in thellier_magic
    zed = make_plots(this_specimen, thel_data, cnt)
  File "/Users/nebula/Python/PmagPy/pmagpy/ipmag.py", line 10191, in make_plots
    araiblock, field = pmag.sortarai(spec_df, this_specimen, 0, version=3)
  File "/Users/nebula/Python/PmagPy/pmagpy/pmag.py", line 7143, in sortarai
    idec = float(irec[dec_key])
TypeError: float() argument must be a string or a number, not 'NoneType'
```

This happens both with the older version I was initially testing on (16302) and the up-to-date version (16583).

The error is caused by a missing `dir_dec` value on measurement 1657.  @njarboe and @rminnet -- I'm wondering if this is a problem I should try to deal with in PmagPy directly, or if this is something that should have been caught by validations?  

Also, it seems that there is an initial blank column (an extra leading tab in each line after the header), which seems to be ignored in the MagIC display interface, but shows up in Open Office or when read in by PmagPy.

**Comment by njarboe** [comment]
This should be caught by the type() validation rule which is not yet implemented (Top of Rupert's list, and currently working on it. Should be in place soon). You should not have to deal with such data in PmagPy. If you can throw an error message in this case along the line "Data file is likely to be malformed or missing required data.", that could be useful to people who try and create their own MagIC data format files to analyze their data with PmagPy and make mistakes.

I'll try fixing up the data file and take another look.
