### ISSUE TITLE
thellier_gui upset about measurement_number

### ISSUE THREAD

**Issue by ltauxe** [PmagPy/PmagPy#502]
**What command was run:**

thellier_gui.py

**What happened:**

Traceback (most recent call last):
  File "/Users/ltauxe/PmagPy/programs/pmag_gui.py", line 467, in on_btn_thellier_gui
    evt_quit=ThellierGuiExitEvent)
  File "/Users/ltauxe/PmagPy/programs/thellier_gui.py", line 400, in __init__
    self.Data, self.Data_hierarchy = self.get_data()
  File "/Users/ltauxe/PmagPy/programs/thellier_gui.py", line 6637, in get_data
    float(rec['measurement_number'])
TypeError: float() argument must be a string or a number, not 'NoneType'

**What I expected to happen:**

measurement_number is not even a required field in the current data model.  This error should not be happening.  perhaps measurements.sequence is what is desired?   

**Data file(s):**

[measurements.txt](https://github.com/PmagPy/PmagPy/files/2793369/measurements.txt)

**Screenshot(s):**

**PmagPy version:**

**Comment by ltauxe** [comment]
i fixed this by changing the except ValueError: to except:
