### ISSUE TITLE
Interpretation editor not launching within demag_gui

### ISSUE THREAD

**Issue by Swanson-Hysell** [PmagPy/PmagPy#51]
Seems to be an issue with the recent changes related to font_type. See Traceback below:

```
Traceback (most recent call last):
  File "/Users/Laurentia/PmagPy/demag_gui.py", line 3969, in on_menu_edit_interpretations
    self.interpretation_editor = EditFitFrame(self)
  File "/Users/Laurentia/PmagPy/demag_gui.py", line 5039, in __init__
    self.init_UI()
  File "/Users/Laurentia/PmagPy/demag_gui.py", line 5049, in init_UI
    font1 = wx.Font(10, wx.SWISS, wx.NORMAL, wx.NORMAL, False, self.font_type)
AttributeError: 'EditFitFrame' object has no attribute 'font_type'
```

**Comment by Caoimhinmg** [comment]
forgot to carry a variable from the main gui to the editor. I've fixed it now.
