### ISSUE TITLE
thellier_magic ZeroDivisionError

### ISSUE THREAD

**Issue by moonshoes87** [PmagPy/PmagPy#575]
Presumably related to #483 

**What command was run:**

`download_magic.py -f magic_contribution_13238.txt`
`thellier_magic.py -spc 11CL8604B`

**What happened:**

```
Traceback (most recent call last):
  File "/Users/nebula/Python/PmagPy/programs/thellier_magic.py", line 109, in <module>
    main()
  File "/Users/nebula/Python/PmagPy/programs/thellier_magic.py", line 100, in main
    spec, n_specs, save_plots, fmt, interactive)
  File "/Users/nebula/Python/PmagPy/pmagpy/ipmag.py", line 10754, in thellier_magic
    zed = make_plots(this_specimen, thel_data, cnt)
  File "/Users/nebula/Python/PmagPy/pmagpy/ipmag.py", line 10700, in make_plots
    AZD, araiblock, zijdblock, this_specimen, unit_string)  # make the plots
  File "/Users/nebula/Python/PmagPy/pmagpy/pmagplotlib.py", line 1284, in plot_arai_zij
    plot_zij(ZED['zijd'], zijdblock, angle, s, norm)
  File "/Users/nebula/Python/PmagPy/pmagpy/pmagplotlib.py", line 681, in plot_zij
    fact = (1./datablock[0][3])   # normalize to NRM=1
ZeroDivisionError: float division by zero
```
**What I expected to happen:**

Plotting without errors.

**Data file(s):**

[magic_contribution_13238.txt](https://github.com/PmagPy/PmagPy/files/3164208/magic_contribution_13238.txt)

**Screenshot(s):**

**PmagPy version:**

**Comment by moonshoes87** [comment]
@ltauxe, if you have a chance -- is this solution ok, or do you think there is something deeper going on here?  You can see my commit https://github.com/PmagPy/PmagPy/commit/150e45405b92aa6164869467540da8087065adc4 which basically just says don't norm if you get a ZeroDivisionError...

**Comment by moonshoes87** [comment]
I'm going to assume this is ok.
