### ISSUE TITLE
Opening standalone Pmag and getting GUI KeyError: 'derived_value'

### ISSUE THREAD

**Issue by moonshoes87** [PmagPy/PmagPy#590]
**What command was run:**

Opening standalone Pmag GUI on windows

**What happened:**
```
-I- PmagPy icon file not found -- skipping
-I- Read in any available data from working directory
-I- Using online data model
-I- Couldn't connect to earthref.org, using cached method codes
-I- Using cached method codes
-I- Using cached vocabularies
Traceback (most recent call last):
  File "pmagpy\contribution_builder.py", line 48, in __init__
AttributeError: type object 'Contribution' has no attribute 'vocab'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "site-packages\pandas\core\indexes\base.py", line 2657, in get_loc
  File "pandas/_libs/index.pyx", line 108, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 132, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1601, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1608, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'derived_value'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "programs\pmag_gui.py", line 871, in <module>
  File "programs\pmag_gui.py", line 860, in main
  File "programs\pmag_gui.py", line 81, in __init__
  File "programs\pmag_gui.py", line 349, in get_dir
  File "programs\pmag_gui.py", line 378, in on_change_dir_button
  File "programs\pmag_gui.py", line 393, in on_finish_change_dir
  File "programs\pmag_gui.py", line 139, in get_wd_data
  File "pmagpy\contribution_builder.py", line 50, in __init__
  File "pmagpy\controlled_vocabularies3.py", line 46, in __init__
  File "pmagpy\controlled_vocabularies3.py", line 379, in get_all_vocabulary
  File "pmagpy\controlled_vocabularies3.py", line 258, in get_controlled_vocabularies
  File "site-packages\pandas\core\frame.py", line 2927, in __getitem__
  File "site-packages\pandas\core\indexes\base.py", line 2659, in get_loc
  File "pandas/_libs/index.pyx", line 108, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 132, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1601, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1608, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'derived_value'
```

**What I expected to happen:**

**Data file(s):**

**Screenshot(s):**

**PmagPy version:**

**Comment by moonshoes87** [comment]
Possibly the problem might be the mismatch between online data model and cached method codes.  A temporary solution should be disabling WiFi, or (for non-standalone users) setting pmag_env/set_env.py line 10 to:

    OFFLINE = True

I will investigate more when I have time.
