### ISSUE TITLE
gui troubles

### ISSUE THREAD

**Issue by ltauxe** [PmagPy/PmagPy#595]
**What command was run:**
I downloaded the attached file from MagIC, unpacked with download_magic.py, and then ran, 
for example,  demag_gui.py -WD .

only if the criteria.txt file is present does this bug happen.  the criteria.txt file is really useless with this file and should not have been there in MagIC.  but can we put in a trap if criteria.txt does not contain the table_column column then, the criteria file is ignored and we can move on?  

lisa

**What happened:**
ltauxe:$ demag_gui.py -WD .
-I- You are in log mode.
    You can check your log output in "demag_gui.log"
    If you prefer verbose output to your Terminal/Command prompt, run "demag_gui.py -v"
Traceback (most recent call last):
  File "/Users/ltauxe/anaconda3/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 3078, in get_loc
    return self._engine.get_loc(key)
  File "pandas/_libs/index.pyx", line 140, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 162, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1492, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1500, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'table_column'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/ltauxe/PmagPy/programs/demag_gui.py", line 8683, in <module>
    main()
  File "/Users/ltauxe/PmagPy/programs/demag_gui.py", line 8679, in main
    start(WD=WD, write_to_log_file=write_to_log_file, DM=data_model, meas_file=meas_file)
  File "/Users/ltauxe/PmagPy/programs/demag_gui.py", line 8651, in start
    meas_file=meas_file)
  File "/Users/ltauxe/PmagPy/programs/demag_gui.py", line 207, in __init__
    self.acceptance_criteria = self.read_criteria_file()
  File "/Users/ltauxe/PmagPy/programs/demag_gui.py", line 2929, in read_criteria_file
    'criteria'], custom_filenames={'criteria': criteria_file_name})
  File "/Users/ltauxe/PmagPy/pmagpy/contribution_builder.py", line 74, in __init__
    self.add_magic_table(name, fname=self.filenames[name])
  File "/Users/ltauxe/PmagPy/pmagpy/contribution_builder.py", line 157, in add_magic_table
    dmodel=self.data_model)
  File "/Users/ltauxe/PmagPy/pmagpy/contribution_builder.py", line 1375, in __init__
    self.df.index = self.df['table_column']
  File "/Users/ltauxe/anaconda3/lib/python3.6/site-packages/pandas/core/frame.py", line 2688, in __getitem__
    return self._getitem_column(key)
  File "/Users/ltauxe/anaconda3/lib/python3.6/site-packages/pandas/core/frame.py", line 2695, in _getitem_column
    return self._get_item_cache(key)
  File "/Users/ltauxe/anaconda3/lib/python3.6/site-packages/pandas/core/generic.py", line 2489, in _get_item_cache
    values = self._data.get(item)
  File "/Users/ltauxe/anaconda3/lib/python3.6/site-packages/pandas/core/internals.py", line 4115, in get
    loc = self.items.get_loc(item)
  File "/Users/ltauxe/anaconda3/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 3080, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas/_libs/index.pyx", line 140, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 162, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1492, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1500, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'table_column'
/Users/ltauxe/anaconda3/bin/pythonw: line 3: 65897 Segmentation fault: 11  /Users/ltauxe/anaconda3/python.app/Contents/MacOS/python "$@"

**What I expected to happen:**

for it to work.   
[magic_contribution_16676.txt](https://github.com/PmagPy/PmagPy/files/3753409/magic_contribution_16676.txt)

**Data file(s):**
this seems to happen on all data files i've tried.  

**Screenshot(s):**

**PmagPy version:**

**Comment by ltauxe** [comment]
oh.  i found the bug in contribution_builder and fixed it (it just ignores bad criteria files).
