### ISSUE TITLE
requirement of 'pmagpy-cli' distribution throwing error in pmag_gui

### ISSUE THREAD

**Issue by Swanson-Hysell** [PmagPy/PmagPy#60]
It seems that there is now a requirement within the PmagPy/programs/__init__.py file for the 'pmagpy-cli' distribution to be installed. This error gets thrown when trying to convert files via cit_magic.py through pmag_gui. We would like to be able to run straight from the master without doing a pip installation (given that the pip installed version is not working with Anaconda) and simply having the path set.

```
Traceback (most recent call last):
  File "/Users/Laurentia/PmagPy/dialogs/pmag_basic_dialogs.py", line 1018, in on_okButton
    import programs.cit_magic as cit_magic
  File "/Users/Laurentia/PmagPy/programs/__init__.py", line 21, in <module>
    print pkg_resources.get_distribution('pmagpy-cli')
  File "/Users/Laurentia/anaconda/envs/python2/lib/python2.7/site-packages/setuptools-20.1.1-py2.7.egg/pkg_resources/__init__.py", line 540, in get_distribution
    
  File "/Users/Laurentia/anaconda/envs/python2/lib/python2.7/site-packages/setuptools-20.1.1-py2.7.egg/pkg_resources/__init__.py", line 420, in get_provider
    
  File "/Users/Laurentia/anaconda/envs/python2/lib/python2.7/site-packages/setuptools-20.1.1-py2.7.egg/pkg_resources/__init__.py", line 941, in require
    
  File "/Users/Laurentia/anaconda/envs/python2/lib/python2.7/site-packages/setuptools-20.1.1-py2.7.egg/pkg_resources/__init__.py", line 828, in resolve
    
pkg_resources.DistributionNotFound: The 'pmagpy-cli' distribution was not found and is required by the application
```

**Comment by moonshoes87** [comment]
Ah — I hadn’t realized that __init__ would be run when programs is imported directly from the PmagPy repo.  I’ll push the solution ASAP.

**Comment by Swanson-Hysell** [comment]
Yes. That maintenance of a number of different ways to run the programs is an issue. I do think that being able to run the programs straight from their own directory with the paths set right is a good thing to maintain. I would likely feel differently if the pip installation of the guis worked with the Anaconda distro.

There was a syntax error in the fix:

```
Traceback (most recent call last):
  File "/Users/Laurentia/PmagPy/dialogs/pmag_basic_dialogs.py", line 1018, in on_okButton
    import programs.cit_magic as cit_magic
  File "/Users/Laurentia/PmagPy/programs/__init__.py", line 19
    except 
          ^
SyntaxError: invalid syntax
```
But I think that I fixed it and all seems to be well now.

Thanks!

**Comment by moonshoes87** [comment]
Thanks!
