### ISSUE TITLE
Lisa's recent contribution, Tauxe et al. (2015), fails to load into demag_gui

### ISSUE THREAD

**Issue by njarboe** [PmagPy/PmagPy#614]
When I unpack this file:
[magic_contribution_16761.txt](https://github.com/PmagPy/PmagPy/files/4447491/magic_contribution_16761.txt)
and run pmag_gui and then try to open the data in demag_gui, I get the error below, but this file works:
[magic_contribution_16680.txt](https://github.com/PmagPy/PmagPy/files/4447528/magic_contribution_16680.txt)

(base) kamacite:testing2020-04-07 njarboe$ pmag_gui.py
-I- Importing Pmag GUI dependencies
-I- Starting Pmag GUI - please be patient
objc[52432]: Class FIFinderSyncExtensionHost is implemented in both /System/Library/PrivateFrameworks/FinderKit.framework/Versions/A/FinderKit (0x7fff92c353d8) and /System/Library/PrivateFrameworks/FileProvider.framework/OverrideBundles/FinderSyncCollaborationFileProviderOverride.bundle/Contents/MacOS/FinderSyncCollaborationFileProviderOverride (0x1a25df0f50). One of the two will be used. Which one is undefined.
-I- Read in any available data from working directory
-I- Using online data model
-I- Getting method codes from earthref.org
-I- Importing controlled vocabularies from https://earthref.org
-I- Read in any available data from working directory
-I- running python script:
 demag_gui.py -WD /Users/njarboe/Dropbox/MagIC/paleomagnetism.org/testing2020-04-07
data model: 3.0
Traceback (most recent call last):
  File "/Users/njarboe/git/pmagpy/PmagPy/programs/pmag_gui.py", line 444, in on_btn_demag_gui
    evt_quit=DemagGuiExitEvent)
  File "/Users/njarboe/git/pmagpy/PmagPy/programs/demag_gui.py", line 259, in __init__
    self.Data_info = self.get_data_info()  # Read  er_* data
  File "/Users/njarboe/git/pmagpy/PmagPy/programs/demag_gui.py", line 4541, in get_data_info
    samp_container.front_and_backfill(['azimuth', 'dip'])
  File "/Users/njarboe/git/pmagpy/PmagPy/pmagpy/contribution_builder.py", line 1819, in front_and_backfill
    tester = short_df.groupby(short_df.index, sort=False).fillna(method='ffill')
  File "/Users/njarboe/anaconda3/lib/python3.7/site-packages/pandas/core/groupby/groupby.py", line 644, in wrapper
    return self.apply(curried)
  File "/Users/njarboe/anaconda3/lib/python3.7/site-packages/pandas/core/groupby/groupby.py", line 735, in apply
    result = self._python_apply_general(f)
  File "/Users/njarboe/anaconda3/lib/python3.7/site-packages/pandas/core/groupby/groupby.py", line 754, in _python_apply_general
    keys, values, not_indexed_same=mutated or self.mutated
  File "/Users/njarboe/anaconda3/lib/python3.7/site-packages/pandas/core/groupby/generic.py", line 1213, in _wrap_applied_output
    return self._concat_objects(keys, values, not_indexed_same=not_indexed_same)
  File "/Users/njarboe/anaconda3/lib/python3.7/site-packages/pandas/core/groupby/groupby.py", line 988, in _concat_objects
    result = result.reindex(ax, axis=self.axis)
  File "/Users/njarboe/anaconda3/lib/python3.7/site-packages/pandas/util/_decorators.py", line 227, in wrapper
    return func(*args, **kwargs)
  File "/Users/njarboe/anaconda3/lib/python3.7/site-packages/pandas/core/frame.py", line 3856, in reindex
    return self._ensure_type(super().reindex(**kwargs))
  File "/Users/njarboe/anaconda3/lib/python3.7/site-packages/pandas/core/generic.py", line 4544, in reindex
    axes, level, limit, tolerance, method, fill_value, copy
  File "/Users/njarboe/anaconda3/lib/python3.7/site-packages/pandas/core/frame.py", line 3744, in _reindex_axes
    index, method, copy, level, fill_value, limit, tolerance
  File "/Users/njarboe/anaconda3/lib/python3.7/site-packages/pandas/core/frame.py", line 3766, in _reindex_index
    allow_dups=False,
  File "/Users/njarboe/anaconda3/lib/python3.7/site-packages/pandas/core/generic.py", line 4613, in _reindex_with_indexers
    copy=copy,
  File "/Users/njarboe/anaconda3/lib/python3.7/site-packages/pandas/core/internals/managers.py", line 1251, in reindex_indexer
    self.axes[axis]._can_reindex(indexer)
  File "/Users/njarboe/anaconda3/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 3099, in _can_reindex
    raise ValueError("cannot reindex from a duplicate axis")
ValueError: cannot reindex from a duplicate axis

**Comment by njarboe** [comment]
I recently reinstalled anaconda and went through the cookbook steps, if that is useful.

**Comment by njarboe** [comment]
I also get the same error when I try to look at a file I have created for the MIT group:
[Jack-Hills_08.Apr.2020.txt](https://github.com/PmagPy/PmagPy/files/4452991/Jack-Hills_08.Apr.2020.txt)
(base) kamacite:Weiss2018Set2 njarboe$ pmag_gui.py
-I- Importing Pmag GUI dependencies
-I- Starting Pmag GUI - please be patient
objc[67333]: Class FIFinderSyncExtensionHost is implemented in both /System/Library/PrivateFrameworks/FinderKit.framework/Versions/A/FinderKit (0x7fff92c353d8) and /System/Library/PrivateFrameworks/FileProvider.framework/OverrideBundles/FinderSyncCollaborationFileProviderOverride.bundle/Contents/MacOS/FinderSyncCollaborationFileProviderOverride (0x1a21f47f50). One of the two will be used. Which one is undefined.
-I- Read in any available data from working directory
-I- Using online data model
-I- Getting method codes from earthref.org
-I- Importing controlled vocabularies from https://earthref.org
-I- Read in any available data from working directory
-I- running python script:
 download_magic.py -f Jack-Hills_08.Apr.2020.txt -WD /Users/njarboe/Dropbox/MagIC/people/Shah/data2020-04-01/Weiss2018Set2 -ID /Users/njarboe/Dropbox/MagIC/people/Shah/data2020-04-01/Weiss2018Set2
working on:  'images'
28  records written to file  /Users/njarboe/Dropbox/MagIC/people/Shah/data2020-04-01/Weiss2018Set2/images.txt
images  data put in  /Users/njarboe/Dropbox/MagIC/people/Shah/data2020-04-01/Weiss2018Set2/images.txt
working on:  'locations'
1  records written to file  /Users/njarboe/Dropbox/MagIC/people/Shah/data2020-04-01/Weiss2018Set2/locations.txt
locations  data put in  /Users/njarboe/Dropbox/MagIC/people/Shah/data2020-04-01/Weiss2018Set2/locations.txt
working on:  'measurements'
253  records written to file  /Users/njarboe/Dropbox/MagIC/people/Shah/data2020-04-01/Weiss2018Set2/measurements.txt
measurements  data put in  /Users/njarboe/Dropbox/MagIC/people/Shah/data2020-04-01/Weiss2018Set2/measurements.txt
working on:  'samples'
13  records written to file  /Users/njarboe/Dropbox/MagIC/people/Shah/data2020-04-01/Weiss2018Set2/samples.txt
samples  data put in  /Users/njarboe/Dropbox/MagIC/people/Shah/data2020-04-01/Weiss2018Set2/samples.txt
working on:  'sites'
4  records written to file  /Users/njarboe/Dropbox/MagIC/people/Shah/data2020-04-01/Weiss2018Set2/sites.txt
sites  data put in  /Users/njarboe/Dropbox/MagIC/people/Shah/data2020-04-01/Weiss2018Set2/sites.txt
working on:  'specimens'
13  records written to file  /Users/njarboe/Dropbox/MagIC/people/Shah/data2020-04-01/Weiss2018Set2/specimens.txt
specimens  data put in  /Users/njarboe/Dropbox/MagIC/people/Shah/data2020-04-01/Weiss2018Set2/specimens.txt
-I- running python script:
 demag_gui.py -WD /Users/njarboe/Dropbox/MagIC/people/Shah/data2020-04-01/Weiss2018Set2
data model: 3.0
Traceback (most recent call last):
  File "/Users/njarboe/git/pmagpy/PmagPy/programs/pmag_gui.py", line 444, in on_btn_demag_gui
    evt_quit=DemagGuiExitEvent)
  File "/Users/njarboe/git/pmagpy/PmagPy/programs/demag_gui.py", line 259, in __init__
    self.Data_info = self.get_data_info()  # Read  er_* data
  File "/Users/njarboe/git/pmagpy/PmagPy/programs/demag_gui.py", line 4541, in get_data_info
    samp_container.front_and_backfill(['azimuth', 'dip'])
  File "/Users/njarboe/git/pmagpy/PmagPy/pmagpy/contribution_builder.py", line 1819, in front_and_backfill
    tester = short_df.groupby(short_df.index, sort=False).fillna(method='ffill')
  File "/Users/njarboe/anaconda3/lib/python3.7/site-packages/pandas/core/groupby/groupby.py", line 644, in wrapper
    return self.apply(curried)
  File "/Users/njarboe/anaconda3/lib/python3.7/site-packages/pandas/core/groupby/groupby.py", line 735, in apply
    result = self._python_apply_general(f)
  File "/Users/njarboe/anaconda3/lib/python3.7/site-packages/pandas/core/groupby/groupby.py", line 754, in _python_apply_general
    keys, values, not_indexed_same=mutated or self.mutated
  File "/Users/njarboe/anaconda3/lib/python3.7/site-packages/pandas/core/groupby/generic.py", line 1213, in _wrap_applied_output
    return self._concat_objects(keys, values, not_indexed_same=not_indexed_same)
  File "/Users/njarboe/anaconda3/lib/python3.7/site-packages/pandas/core/groupby/groupby.py", line 988, in _concat_objects
    result = result.reindex(ax, axis=self.axis)
  File "/Users/njarboe/anaconda3/lib/python3.7/site-packages/pandas/util/_decorators.py", line 227, in wrapper
    return func(*args, **kwargs)
  File "/Users/njarboe/anaconda3/lib/python3.7/site-packages/pandas/core/frame.py", line 3856, in reindex
    return self._ensure_type(super().reindex(**kwargs))
  File "/Users/njarboe/anaconda3/lib/python3.7/site-packages/pandas/core/generic.py", line 4544, in reindex
    axes, level, limit, tolerance, method, fill_value, copy
  File "/Users/njarboe/anaconda3/lib/python3.7/site-packages/pandas/core/frame.py", line 3744, in _reindex_axes
    index, method, copy, level, fill_value, limit, tolerance
  File "/Users/njarboe/anaconda3/lib/python3.7/site-packages/pandas/core/frame.py", line 3766, in _reindex_index
    allow_dups=False,
  File "/Users/njarboe/anaconda3/lib/python3.7/site-packages/pandas/core/generic.py", line 4613, in _reindex_with_indexers
    copy=copy,
  File "/Users/njarboe/anaconda3/lib/python3.7/site-packages/pandas/core/internals/managers.py", line 1251, in reindex_indexer
    self.axes[axis]._can_reindex(indexer)
  File "/Users/njarboe/anaconda3/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 3099, in _can_reindex
    raise ValueError("cannot reindex from a duplicate axis")
ValueError: cannot reindex from a duplicate axis

**Comment by moonshoes87** [comment]
I will try to look at this next weekend or early next week, thanks Nick.

**Comment by njarboe** [comment]
Great. You can ignore the Jack_Hills file. I have discovered a few more changes that need to be made in the MIT SQUID conversion program I am working on.

**Comment by moonshoes87** [comment]
This is an issue of pandas 0.25 vs pandas 1.0.3.  It should be working now.

**Comment by njarboe** [comment]
This is working now on the Jack_Hills data file also. Great.
