### ISSUE TITLE
Issues with gobing.py

### ISSUE THREAD

**Issue by sarah-potatoes** [PmagPy/PmagPy#616]
**What command was run:**
gobing.py -f vectors.txt 

**What happened:**
Traceback (most recent call last):
  File "/Users/Sarah/anaconda3/bin/gobing.py", line 10, in <module>
    sys.exit(main())
  File "/Users/Sarah/anaconda3/lib/python3.7/site-packages/programs/gobing.py", line 52, in main
    bpars=pmag.dobingham(DIs)
  File "/Users/Sarah/anaconda3/lib/python3.7/site-packages/pmagpy/pmag.py", line 4737, in dobingham
    k1, k2 = binglookup(w1, w2)
  File "/Users/Sarah/anaconda3/lib/python3.7/site-packages/pmagpy/pmag.py", line 4681, in binglookup
    k1, k2 = float(K[w2][w1][0]), float(K[w2][w1][1])
KeyError: '0.12'

**What I expected to happen:**
I expected the normal output of 
       mean dec, mean inc, Eta, Deta, Ieta, Zeta, Zdec, Zinc, N

It is interesting to note that a subset of vectors.txt (such as the 1st 20 entries instead of all 28) will work. I've noticed this issue a few times on other vector averaging commands. Often removing one line will fix it, but there seems to be no reason why a particular line is causing problems, and it is hard to find without a lot of trial and error (making automation difficult).
**Data file(s):**
[vectors.txt](https://github.com/PmagPy/PmagPy/files/4530856/vectors.txt)

**Screenshot(s):**

**PmagPy version:**
4.2.43

**Comment by moonshoes87** [comment]
@ltauxe, do you want to look at this, or should I?

**Comment by moonshoes87** [comment]
@sarah-potatoes, sorry this took me so long!  I can't reproduce this error with the data file you've attached:

gobing.py -f vectors.txt
  197.5    33.2    12.5   112.1    -7.0    11.3   212.6   -55.9 20

but it looks like you only included the first 20 lines, so I am guessing that excludes the problematic lines.  Please attach the full file, and I will have a look!

**Comment by sarah-potatoes** [comment]
Sorry for my delay too! Here's another sample set that runs errors:

[bingtest.txt](https://github.com/PmagPy/PmagPy/files/4639189/bingtest.txt)

When I run gobing.py -f bingtest.txt 

my output looks like this:
Traceback (most recent call last):
  File "/Users/Sarah/anaconda3/bin/gobing.py", line 10, in <module>
    sys.exit(main())
  File "/Users/Sarah/anaconda3/lib/python3.7/site-packages/programs/gobing.py", line 52, in main
    bpars=pmag.dobingham(DIs)
  File "/Users/Sarah/anaconda3/lib/python3.7/site-packages/pmagpy/pmag.py", line 4737, in dobingham
    k1, k2 = binglookup(w1, w2)
  File "/Users/Sarah/anaconda3/lib/python3.7/site-packages/pmagpy/pmag.py", line 4681, in binglookup
    k1, k2 = float(K[w2][w1][0]), float(K[w2][w1][1])
KeyError: '0.16'

**Comment by ltauxe** [comment]
I think I fixed this, but I'm not sure it will work universally.  Could someone check it?  thanks

**Comment by sarah-potatoes** [comment]
I updated to version 4.2.45 and it seems to have resolved the issue, thanks!
