### ISSUE TITLE
Pierrick Roperch's MagIC data file throws an error in Demag GUI

### ISSUE THREAD

**Issue by njarboe** [PmagPy/PmagPy#620]
Pierrick Roperch is working on creating a MagIC file export for his software. His file passes validation but when I try and open it up in pmag gui using demag gui I get this error:

pmag_gui.py
-I- Importing Pmag GUI dependencies
-I- Starting Pmag GUI - please be patient
objc[88569]: Class FIFinderSyncExtensionHost is implemented in both /System/Library/PrivateFrameworks/FinderKit.framework/Versions/A/FinderKit (0x7fff907603d8) and /System/Library/PrivateFrameworks/FileProvider.framework/OverrideBundles/FinderSyncCollaborationFileProviderOverride.bundle/Contents/MacOS/FinderSyncCollaborationFileProviderOverride (0x1a3163bf50). One of the two will be used. Which one is undefined.
-I- Read in any available data from working directory
-I- Using online data model
-I- Getting method codes from earthref.org
-I- Importing controlled vocabularies from https://earthref.org
-I- Read in any available data from working directory
-I- running python script:
 demag_gui.py -WD /Users/njarboe/Dropbox/MagIC/people/Roperch/DataFiles2020-07-06/dataFiles
data model: 3.0
Traceback (most recent call last):
  File "/Users/njarboe/git/pmagpy/PmagPy/programs/pmag_gui.py", line 444, in on_btn_demag_gui
    evt_quit=DemagGuiExitEvent)
  File "/Users/njarboe/git/pmagpy/PmagPy/programs/demag_gui.py", line 259, in __init__
    self.Data_info = self.get_data_info()  # Read  er_* data
  File "/Users/njarboe/git/pmagpy/PmagPy/programs/demag_gui.py", line 4585, in get_data_info
    data_er_locations = loc2_data.to_dict('index')
  File "/Users/njarboe/anaconda3/lib/python3.7/site-packages/pandas/core/frame.py", line 1433, in to_dict
    raise ValueError("DataFrame index must be unique for orient='index'.")
ValueError: DataFrame index must be unique for orient='index'.

[magic_contribution_16878.txt](https://github.com/PmagPy/PmagPy/files/4969532/magic_contribution_16878.txt)

**Comment by njarboe** [comment]
Lisa commented out the line
data_er_locations = loc2_data.to_dict('index') #TRY
from demag gui and that fixed the problem.
It breaks on location tables that have two locations with the same name. This will be the case if we have data for a location on the geographic and stratigraphic directions, for example. 
I checked that pmag_gui produced a valid file after reading in a magic data file and exporting it. It passed validation and preserved the repeated location name rows in the file.
