### ISSUE TITLE
empty string/np.nan/int vs float problem in upload magic validations

### ISSUE THREAD

**Issue by moonshoes87** [PmagPy/PmagPy#640]
I just started working on the upload magic validation in Pmag GUI.  It looks like the np.nan vs. empty string problem is still happening at least with some versions of pandas.

This is what I have for pandas version:

```
pandas                    1.3.0            py37h23ab428_0  
```

And the error message:

```
Traceback (most recent call last):
  File "/Users/nebula/Python/PmagPy/programs/pmag_gui.py", line 680, in on_btn_upload
    upload_file, val_response, dummy1, dummy2 = ipmag.upload_magic(concat=False, input_dir_path=self.WD, dir_path=self.WD)
  File "/Users/nebula/Python/PmagPy/pmagpy/ipmag.py", line 4811, in upload_magic
    df.loc[df['int_md'].astype('float')<0,'int_md']=np.nan
  File "/Users/nebula/opt/anaconda3/envs/new_pmagpy_1/lib/python3.7/site-packages/pandas/core/generic.py", line 5806, in astype
    new_data = self._mgr.astype(dtype=dtype, copy=copy, errors=errors)
  File "/Users/nebula/opt/anaconda3/envs/new_pmagpy_1/lib/python3.7/site-packages/pandas/core/internals/managers.py", line 414, in astype
    return self.apply("astype", dtype=dtype, copy=copy, errors=errors)
  File "/Users/nebula/opt/anaconda3/envs/new_pmagpy_1/lib/python3.7/site-packages/pandas/core/internals/managers.py", line 327, in apply
    applied = getattr(b, f)(**kwargs)
  File "/Users/nebula/opt/anaconda3/envs/new_pmagpy_1/lib/python3.7/site-packages/pandas/core/internals/blocks.py", line 592, in astype
    new_values = astype_array_safe(values, dtype, copy=copy, errors=errors)
  File "/Users/nebula/opt/anaconda3/envs/new_pmagpy_1/lib/python3.7/site-packages/pandas/core/dtypes/cast.py", line 1300, in astype_array_safe
    new_values = astype_array(values, dtype, copy=copy)
  File "/Users/nebula/opt/anaconda3/envs/new_pmagpy_1/lib/python3.7/site-packages/pandas/core/dtypes/cast.py", line 1248, in astype_array
    values = astype_nansafe(values, dtype, copy=copy)
  File "/Users/nebula/opt/anaconda3/envs/new_pmagpy_1/lib/python3.7/site-packages/pandas/core/dtypes/cast.py", line 1192, in astype_nansafe
    return arr.astype(dtype, copy=True)
ValueError: could not convert string to float: 
```

With this contribution:
[Jan-Mayen_Spitsbergen_29.Jul.2021.txt](https://github.com/PmagPy/PmagPy/files/7233097/Jan-Mayen_Spitsbergen_29.Jul.2021.txt)

**Comment by moonshoes87** [comment]
The problem is the same with the latest pandas:

```
pandas                    1.3.2            py37h5008ddb_0  
```

and with the McMurdo test directory.
