### ISSUE TITLE
pmag_gui puts in extra lines at the end of tables when editing

### ISSUE THREAD

**Issue by ltauxe** [PmagPy/PmagPy#652]
**What command was run:**

pmag_gui.py

**What happened:**

tried editing table  button 3 from a data set that passed validation.  after saving the edited files there was an extra, erroneous, line at the end of the table and the contribution failed validation.

**What I expected to happen:**

I expected the edited file to pass validation as it had before minor editing. 

**Data file(s):**

run 'unpack' from pmag_gui.py then try editing a column and saving it: 
[magic_contribution_19534.txt](https://github.com/PmagPy/PmagPy/files/8715916/magic_contribution_19534.txt)

**Screenshot(s):**

**PmagPy version:**
pmagpy-4.2.102

**Comment by ltauxe** [comment]
actually - it is the OSX standalone version that does this.  version 4.2.102 doesn't do the editing at all!  it hangs after choosing column headers with this error: 

Traceback (most recent call last):
  File "/Users/ltauxe/PmagPy/dialogs/ErMagicBuilder.py", line 253, in on_okButton
    self.main_frame.init_check_window()
  File "/Users/ltauxe/PmagPy/programs/pmag_gui.py", line 545, in init_check_window
    self.check_dia = pmag_er_magic_dialogs.ErMagicCheckFrame3(self, 'Check Data',
  File "/Users/ltauxe/PmagPy/dialogs/pmag_er_magic_dialogs.py", line 30, in __init__
    self.InitSpecCheck()
  File "/Users/ltauxe/PmagPy/dialogs/pmag_er_magic_dialogs.py", line 43, in InitSpecCheck
    self.grid_frame = grid_frame3.GridFrame(self.contribution, self.WD,
  File "/Users/ltauxe/PmagPy/dialogs/grid_frame3.py", line 71, in __init__
    self.InitUI()
  File "/Users/ltauxe/PmagPy/dialogs/grid_frame3.py", line 282, in InitUI
    self.main_sizer.Add(self.grid_box, 2, flag=wx.ALL|wx.ALIGN_CENTER|wx.EXPAND, border=10)
wx._core.wxAssertionError: C++ assertion "!(flags & (wxALIGN_RIGHT | wxALIGN_CENTRE_HORIZONTAL))" failed at /Users/runner/miniforge3/conda-bld/wxpython_1616628571745/work/ext/wxWidgets/src/common/sizer.cpp(2159) in DoInsert(): Horizontal alignment flags are ignored with wxEXPAND
^C

**Comment by duserzym** [comment]
things should be fine now in https://github.com/PmagPy/PmagPy-Standalone-OSX/releases/tag/4.3.2
