### ISSUE TITLE
pmag_gui.py dc.DrawText() type error using wxpython==4.1.1 

### ISSUE THREAD

**Issue by Swanson-Hysell** [PmagPy/PmagPy#675]
Using @Caoimhinmg most recent commit I am getting a fatal TypeError.

**What command was run:**

Launched pmag_gui.py using a Python 3.10 environment and wxpython==4.1.1 (the version that installs from conda forge). 

**What happened:**

Crashed out with a TypeError giving this Traceback:

```
Traceback (most recent call last):
  File "/Users/unimos/0000_Github/PmagPy/programs/pmag_gui.py", line 887, in <module>
    main()
  File "/Users/unimos/0000_Github/PmagPy/programs/pmag_gui.py", line 876, in main
    app.frame = MagMainFrame(WD=dir_path)
  File "/Users/unimos/0000_Github/PmagPy/programs/pmag_gui.py", line 95, in __init__
    self.refresh_btns()
  File "/Users/unimos/0000_Github/PmagPy/programs/pmag_gui.py", line 323, in refresh_btns
    self.change_dir_button.OnPaint(-1)
  File "/Users/unimos/opt/anaconda3/envs/pmag_gui/lib/python3.10/site-packages/wx/lib/buttons.py", line 496, in OnPaint
    self.DrawLabel(dc, width, height)
  File "/Users/unimos/opt/anaconda3/envs/pmag_gui/lib/python3.10/site-packages/wx/lib/buttons.py", line 456, in DrawLabel
    dc.DrawText(label, (width-tw)/2+dx, (height-th)/2+dy)
TypeError: DC.DrawText(): arguments did not match any overloaded call:
  overload 1: argument 2 has unexpected type 'float'
  overload 2: argument 2 has unexpected type 'float'
```

Here are the packages that I am running in this environment:
```
# packages in environment at /Users/unimos/opt/anaconda3/envs/pmag_gui:
#
# Name                    Version                   Build  Channel
blas                      1.0                         mkl  
bottleneck                1.3.5           py310h4e76f89_0  
brotli                    1.0.9                hca72f7f_7  
brotli-bin                1.0.9                hca72f7f_7  
brotlipy                  0.7.0           py310h90acd4f_1005    conda-forge
bzip2                     1.0.8                h1de35cc_0  
ca-certificates           2022.12.7            h033912b_0    conda-forge
certifi                   2022.12.7          pyhd8ed1ab_0    conda-forge
cffi                      1.15.1          py310ha78151a_3    conda-forge
charset-normalizer        2.1.1              pyhd8ed1ab_0    conda-forge
contourpy                 1.0.5           py310haf03e11_0  
cryptography              39.0.0          py310h23bb4e6_0    conda-forge
cycler                    0.11.0             pyhd3eb1b0_0  
expat                     2.5.0                hf0c8a7f_0    conda-forge
fftw                      3.3.9                h9ed2024_1  
fonttools                 4.25.0             pyhd3eb1b0_0  
freetype                  2.12.1               hd8bbffd_0  
future                    0.18.2          py310hecd8cb5_1  
gettext                   0.21.1               h8a4c099_0    conda-forge
giflib                    5.2.1                haf1e3a3_0  
idna                      3.4                pyhd8ed1ab_0    conda-forge
intel-openmp              2021.4.0          hecd8cb5_3538  
jpeg                      9e                   hca72f7f_0  
kiwisolver                1.4.4           py310hcec6c5f_0  
lcms2                     2.12                 hf1fd2bf_0  
lerc                      3.0                  he9d5cce_0  
libbrotlicommon           1.0.9                hca72f7f_7  
libbrotlidec              1.0.9                hca72f7f_7  
libbrotlienc              1.0.9                hca72f7f_7  
libcxx                    14.0.6               h9765a3e_0  
libdeflate                1.8                  h9ed2024_5  
libffi                    3.4.2                hecd8cb5_6  
libgfortran               5.0.0           11_3_0_hecd8cb5_28  
libgfortran5              11.3.0              h9dfd629_28  
libiconv                  1.17                 hac89ed1_0    conda-forge
libpng                    1.6.37               ha441bb4_0  
libtiff                   4.4.0                h2cd0358_2  
libwebp                   1.2.4                h56c3ce4_0  
libwebp-base              1.2.4                hca72f7f_0  
libzlib                   1.2.13               hfd90126_4    conda-forge
llvm-openmp               14.0.6               h0dcd299_0  
lz4-c                     1.9.4                hcec6c5f_0  
matplotlib                3.6.2           py310hecd8cb5_0  
matplotlib-base           3.6.2           py310h220de94_0  
mkl                       2021.4.0           hecd8cb5_637  
mkl-service               2.4.0           py310hca72f7f_0  
mkl_fft                   1.3.1           py310hf879493_0  
mkl_random                1.2.2           py310hc081a56_0  
munkres                   1.1.4                      py_0  
ncurses                   6.3                  hca72f7f_3  
numexpr                   2.8.4           py310h9638375_0  
numpy                     1.23.5          py310h9638375_0  
numpy-base                1.23.5          py310ha98c3c9_0  
openssl                   1.1.1s               hfd90126_1    conda-forge
packaging                 22.0            py310hecd8cb5_0  
pandas                    1.5.2           py310h3ea8b11_0  
pathlib2                  2.3.7.post1     py310h2ec42d9_2    conda-forge
pillow                    9.3.0           py310h81888ad_1  
pip                       22.3.1          py310hecd8cb5_0  
pthread-stubs             0.4               hc929b4f_1001    conda-forge
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pyopenssl                 23.0.0             pyhd8ed1ab_0    conda-forge
pyparsing                 3.0.9           py310hecd8cb5_0  
pysocks                   1.7.1              pyha2e5f31_6    conda-forge
python                    3.10.8               h218abb5_1  
python-dateutil           2.8.2              pyhd3eb1b0_0  
python.app                1.4             py310h90acd4f_1    conda-forge
python_abi                3.10                    2_cp310    conda-forge
pytz                      2022.7          py310hecd8cb5_0  
readline                  8.2                  hca72f7f_0  
requests                  2.28.1             pyhd8ed1ab_1    conda-forge
scipy                     1.9.3           py310h09290a1_0  
setuptools                65.5.0          py310hecd8cb5_0  
six                       1.16.0             pyhd3eb1b0_1  
sqlite                    3.40.0               h880c91c_0  
tk                        8.6.12               h5d9f67b_0  
tornado                   6.2             py310hca72f7f_0  
tzdata                    2022g                h04d1e81_0  
urllib3                   1.26.13            pyhd8ed1ab_0    conda-forge
wheel                     0.37.1             pyhd3eb1b0_0  
wxpython                  4.1.1           py310h8a1cd26_7    conda-forge
xz                        5.2.8                h6c40b1e_0  
zlib                      1.2.13               hfd90126_4    conda-forge
zstd                      1.5.2                hcb37349_0  
```

Here are the packages in a .yml format:
```
name: pmag_gui
channels:
  - conda-forge
  - defaults
dependencies:
  - blas=1.0=mkl
  - bottleneck=1.3.5=py310h4e76f89_0
  - brotli=1.0.9=hca72f7f_7
  - brotli-bin=1.0.9=hca72f7f_7
  - brotlipy=0.7.0=py310h90acd4f_1005
  - bzip2=1.0.8=h1de35cc_0
  - ca-certificates=2022.12.7=h033912b_0
  - certifi=2022.12.7=pyhd8ed1ab_0
  - cffi=1.15.1=py310ha78151a_3
  - charset-normalizer=2.1.1=pyhd8ed1ab_0
  - contourpy=1.0.5=py310haf03e11_0
  - cryptography=39.0.0=py310h23bb4e6_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - expat=2.5.0=hf0c8a7f_0
  - fftw=3.3.9=h9ed2024_1
  - fonttools=4.25.0=pyhd3eb1b0_0
  - freetype=2.12.1=hd8bbffd_0
  - future=0.18.2=py310hecd8cb5_1
  - gettext=0.21.1=h8a4c099_0
  - giflib=5.2.1=haf1e3a3_0
  - idna=3.4=pyhd8ed1ab_0
  - intel-openmp=2021.4.0=hecd8cb5_3538
  - jpeg=9e=hca72f7f_0
  - kiwisolver=1.4.4=py310hcec6c5f_0
  - lcms2=2.12=hf1fd2bf_0
  - lerc=3.0=he9d5cce_0
  - libbrotlicommon=1.0.9=hca72f7f_7
  - libbrotlidec=1.0.9=hca72f7f_7
  - libbrotlienc=1.0.9=hca72f7f_7
  - libcxx=14.0.6=h9765a3e_0
  - libdeflate=1.8=h9ed2024_5
  - libffi=3.4.2=hecd8cb5_6
  - libgfortran=5.0.0=11_3_0_hecd8cb5_28
  - libgfortran5=11.3.0=h9dfd629_28
  - libiconv=1.17=hac89ed1_0
  - libpng=1.6.37=ha441bb4_0
  - libtiff=4.4.0=h2cd0358_2
  - libwebp=1.2.4=h56c3ce4_0
  - libwebp-base=1.2.4=hca72f7f_0
  - libzlib=1.2.13=hfd90126_4
  - llvm-openmp=14.0.6=h0dcd299_0
  - lz4-c=1.9.4=hcec6c5f_0
  - matplotlib=3.6.2=py310hecd8cb5_0
  - matplotlib-base=3.6.2=py310h220de94_0
  - mkl=2021.4.0=hecd8cb5_637
  - mkl-service=2.4.0=py310hca72f7f_0
  - mkl_fft=1.3.1=py310hf879493_0
  - mkl_random=1.2.2=py310hc081a56_0
  - munkres=1.1.4=py_0
  - ncurses=6.3=hca72f7f_3
  - numexpr=2.8.4=py310h9638375_0
  - numpy=1.23.5=py310h9638375_0
  - numpy-base=1.23.5=py310ha98c3c9_0
  - openssl=1.1.1s=hfd90126_1
  - packaging=22.0=py310hecd8cb5_0
  - pandas=1.5.2=py310h3ea8b11_0
  - pathlib2=2.3.7.post1=py310h2ec42d9_2
  - pillow=9.3.0=py310h81888ad_1
  - pip=22.3.1=py310hecd8cb5_0
  - pthread-stubs=0.4=hc929b4f_1001
  - pycparser=2.21=pyhd8ed1ab_0
  - pyopenssl=23.0.0=pyhd8ed1ab_0
  - pyparsing=3.0.9=py310hecd8cb5_0
  - pysocks=1.7.1=pyha2e5f31_6
  - python=3.10.8=h218abb5_1
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python.app=1.4=py310h90acd4f_1
  - python_abi=3.10=2_cp310
  - pytz=2022.7=py310hecd8cb5_0
  - readline=8.2=hca72f7f_0
  - requests=2.28.1=pyhd8ed1ab_1
  - scipy=1.9.3=py310h09290a1_0
  - setuptools=65.5.0=py310hecd8cb5_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.40.0=h880c91c_0
  - tk=8.6.12=h5d9f67b_0
  - tornado=6.2=py310hca72f7f_0
  - tzdata=2022g=h04d1e81_0
  - urllib3=1.26.13=pyhd8ed1ab_0
  - wheel=0.37.1=pyhd3eb1b0_0
  - wxpython=4.1.1=py310h8a1cd26_7
  - xz=5.2.8=h6c40b1e_0
  - zlib=1.2.13=hfd90126_4
  - zstd=1.5.2=hcb37349_0
prefix: /Users/unimos/opt/anaconda3/envs/pmag_gui
```

**Comment by Caoimhinmg** [comment]
I removed the new method and call that was causing this crash it should revert back to how it worked before.

**Comment by Swanson-Hysell** [comment]
Thanks for doing this. We still need to sort out the button issue. Perhaps, you, @duserzym, and I can have a scheduled work time in early Feb to hack away at this and try some solutions. One solution in the interim could be so put labels under the buttons.
