### ISSUE TITLE
thellier_gui crashes when asked to do anisotropy calculations

### ISSUE THREAD

**Issue by ltauxe** [PmagPy/PmagPy#678]
**What command was run:**

thellier_gui.py => Anisotropy/Calculate anisotropy tensors

**What happened:**

-I- Using anisotropy data
done sort blocks to arai, zij. etc.
    self.GUI_RESOLUTION 1.0
Traceback (most recent call last):
  File "/Users/ltauxe/PmagPy/programs/thellier_gui.py", line 2960, in on_menu_calculate_aniso_tensor
    res, error = self.calculate_anisotropy_tensors(data_model=self.data_model)
  File "/Users/ltauxe/PmagPy/programs/thellier_gui.py", line 3558, in calculate_anisotropy_tensors
    new_data['method_codes'] = new_meths
UnboundLocalError: local variable 'new_meths' referenced before assignment

**What I expected to happen:**

calculate the tensors and then use them

**Data file(s):**

**Screenshot(s):**

**PmagPy version:**
pmagpy-4.2.108

**Comment by ltauxe** [comment]
This is now fixed
