### ISSUE TITLE
aniso_magic.py attribute error

### ISSUE THREAD

**Issue by Swanson-Hysell** [PmagPy/PmagPy#701]
**What command was run:**

Dario Bilardello reports an error running 
```
!aniso_magic.py -f specimens.txt
```
which I replicate

**What happened:**
An error with this Traceback
```
Traceback (most recent call last):
  File "/Users/penokean/0000_GitHub/PmagPy/programs/aniso_magic.py", line 192, in <module>
    main()
  File "/Users/penokean/0000_GitHub/PmagPy/programs/aniso_magic.py", line 179, in main
    ipmag.aniso_magic_nb(infile, samp_file, site_file, verbose,
  File "/Users/penokean/0000_GitHub/PmagPy/pmagpy/ipmag.py", line 10215, in aniso_magic_nb
    return aniso_magic(infile, samp_file, site_file, verbose, ipar, ihext, ivec,
  File "/Users/penokean/0000_GitHub/PmagPy/pmagpy/ipmag.py", line 10294, in aniso_magic
    dir_path = con.directory
AttributeError: 'str' object has no attribute 'directory'
```

**What I expected to happen:**
The program to run without an AttributeError

**PmagPy version:** 4.2.114

**Comment by Swanson-Hysell** [comment]
I have been digging into this bug for a bit and have finally come to the root cause. The issue is that `aniso_magic.py` sends the input parameters to an ipmag function named `ipmag.aniso_magic_nb` as so:

```
ipmag.aniso_magic_nb(infile, samp_file, site_file, verbose,
                         ipar, ihext, ivec, isite, False, iboot,
                         vec, Dir, PDir, crd, num_bootstraps,
                         dir_path, save_plots=save_plots, interactive=interactive,
                         fmt=fmt)
```

That function is itself a wrapper around `ipmag.aniso_magic` (I am not sure why this structure was implemented as I think aniso_magic.py could go straight to `ipmag.aniso_magic`. 

Here is the full code for  `ipmag.aniso_magic_nb()` in which we see that the `False` after `isite` is for a parameter called iloc which is being hardcoded to be false within `aniso_magic.py`.

```
def aniso_magic_nb(infile='specimens.txt', samp_file='samples.txt', site_file='sites.txt', verbose=True,
                   ipar=False, ihext=True, ivec=False, isite=False, iloc=False, iboot=False, vec=0,
                   Dir=[], PDir=[], crd="s", num_bootstraps=1000, dir_path=".", fignum=1,
                   save_plots=True, interactive=False, fmt="png", contribution=None):
    """
    Wrapper for aniso_magic
    """
    return aniso_magic(infile, samp_file, site_file, verbose, ipar, ihext, ivec,
                       isite, iloc, iboot, vec, Dir, PDir, crd, num_bootstraps,
                       dir_path, fignum, save_plots, interactive, fmt, contribution)
```

This `iloc` is being sent into `ipmag.aniso_magic()`, but `iloc` is not a parameter in that function:

```
def aniso_magic(infile='specimens.txt', samp_file='samples.txt', site_file='sites.txt', verbose=True, ipar=False, ihext=True, ivec=False, isite=False, iboot=False, vec=0,Dir=[], PDir=[], crd="s", num_bootstraps=1000, dir_path=".", fignum=1, save_plots=True, interactive=False, fmt="png", contribution=None, image_records=False):
```

The results is that `fmt=fmt` within the function call is being mapped onto contribution. Then when it gets to this code:

```
    if contribution is None:
        # fix directory
        input_dir_path = os.path.realpath(dir_path)
        fnames = {'specimens': infile, 'samples': samp_file, 'sites': site_file}
        con = cb.Contribution(input_dir_path, read_tables=['specimens', 'samples', 'sites', 'contribution'],
                              custom_filenames=fnames)
    else:
        con = contribution
        dir_path = con.directory
```
contribution is not None as it is instead a string like `'png'`.

**Comment by Swanson-Hysell** [comment]
It looks like the goal was to enable plotting by location (some commented out code started along these lines). For the moment, however, we can get rid of the bug by removing sending `iloc` to `ipmag.aniso_magic()` given that it isn't currently defined as a parameter. I have done this in commit https://github.com/PmagPy/PmagPy/commit/08ae59b9479f99825a067e04f89d4b9ec55530af which gets rid of the bug.
