### ISSUE TITLE
demag_gui referencing local variable before assignment

### ISSUE THREAD

**Issue by Swanson-Hysell** [PmagPy/PmagPy#78]
On some data sets, demag_gui is referencing NRM before NRM is assigned:

```
Traceback (most recent call last):
  File "/Users/Laurentia/PmagPy/programs/pmag_gui.py", line 334, in on_run_demag_gui
    demag_gui.main(self.WD, standalone_app=False, parent=self)
  File "/Users/Laurentia/PmagPy/programs/demag_gui.py", line 6513, in main
    frame = Demag_GUI(WD, parent, write_to_log_file=write_to_log_file)
  File "/Users/Laurentia/PmagPy/programs/demag_gui.py", line 194, in __init__
    self.Data,self.Data_hierarchy=self.get_data() # Get data from magic_measurements and rmag_anistropy if exist.
  File "/Users/Laurentia/PmagPy/programs/demag_gui.py", line 3117, in get_data
    DIR=[dec,inc,intensity/NRM]
UnboundLocalError: local variable 'NRM' referenced before assignment
```
@moonshoes87's sleuthing suggests this wasn't an issue at the time point of this commit:
 
This is the oldest commit that works for me (from September 26):  

6430242c987c2db5d1f65477f1bb445ae42cf0e1, added documentation and cleaned up code….

**Comment by ltauxe** [comment]
this sounds reasonable.  why not?  it is mysterious why some samples wouldn’t have an NRM but I’m working on a complicated data set and will track down that problem later.  right now i just need to see the data to know what is missing and what isn’t.  :)  
lisa

**Comment by ltauxe** [comment]
so now i get this error:  

hermione-pro-2:U1456A_MagIC ltauxe$ demag_gui.py -WD .
Traceback (most recent call last):
  File "/Users/ltauxe/Programs/PmagPy/GIT/PmagPy/programs/demag_gui.py", line 6538, in <module>
    main(WD=WD,write_to_log_file=write_to_log_file)
  File "/Users/ltauxe/Programs/PmagPy/GIT/PmagPy/programs/demag_gui.py", line 6522, in main
    app.frame = Demag_GUI(WD, write_to_log_file=write_to_log_file)
  File "/Users/ltauxe/Programs/PmagPy/GIT/PmagPy/programs/demag_gui.py", line 194, in __init__
    self.Data,self.Data_hierarchy=self.get_data() # Get data from magic_measurements and rmag_anistropy if exist.
  File "/Users/ltauxe/Programs/PmagPy/GIT/PmagPy/programs/demag_gui.py", line 3017, in get_data
    self.mag_meas_data.sort(cmp=meas_cmp)
  File "/Users/ltauxe/Programs/PmagPy/GIT/PmagPy/pmagpy/demag_gui_utilities.py", line 36, in meas_cmp
    return int(m1[num_key]) - int(m2[num_key])
ValueError: invalid literal for int() with base 10: ''
Segmentation fault: 11


lisa

**Comment by Caoimhinmg** [comment]
On the same data as last time? It was running fine over here. Well I put in a few extra checks so it doesn't error out while trying to sort measurements. Let me know if it patches the problem.

**Comment by ltauxe** [comment]
well, after much deliberation, demag_gui now fails like this:  

hermione-pro-2:U1456A_MagIC ltauxe$ pmag_gui.py
-I- Importing Pmag GUI dependencies
-I- Starting Pmag GUI - please be patient
-I- Fetching output frame
-I- getting data model, please be patient
-I- running python script:
 demag_gui.py -WD /Users/ltauxe/Dropbox/4Giancarlo/U1456/U1456A_Data/U1456A_MagIC
Traceback (most recent call last):
  File "/Users/ltauxe/Programs/PmagPy/GIT/PmagPy/programs/pmag_gui.py", line 334, in on_run_demag_gui
    demag_gui.main(self.WD, standalone_app=False, parent=self)
  File "/Users/ltauxe/Programs/PmagPy/GIT/PmagPy/programs/demag_gui.py", line 6514, in main
    frame = Demag_GUI(WD, parent, write_to_log_file=write_to_log_file)
  File "/Users/ltauxe/Programs/PmagPy/GIT/PmagPy/programs/demag_gui.py", line 194, in __init__
    self.Data,self.Data_hierarchy=self.get_data() # Get data from magic_measurements and rmag_anistropy if exist.
  File "/Users/ltauxe/Programs/PmagPy/GIT/PmagPy/programs/demag_gui.py", line 3019, in get_data
    if "measurement_number" in rec.keys() and int(rec['measurement_number']) == 1 and "magic_method_codes" in rec.keys() and "LT-NO" not in rec["magic_method_codes"].split(':'):
ValueError: invalid literal for int() with base 10: ''





lisa

**Comment by Caoimhinmg** [comment]
Same problem, different place. Is there a reason why one of the indices for
a measurement isn't a number? I should have fixed it in last commit instead
of casting measurement number as an integer it now just checks if it's
equal to the string value '1'.

**Comment by Swanson-Hysell** [comment]
It seems like this issue has been resolved. If not, go ahead and reopen.
