### ISSUE TITLE
bug in pmag_gui

### ISSUE THREAD

**Issue by ltauxe** [PmagPy/PmagPy#99]
I'm using pmag_gui and tried converting an SIO format file to magic.  this works fine.  but then on the 'next step', i get this bug: 
  File "/Users/ltauxe/Programs/PmagPy/GIT/PmagPy/dialogs/pmag_basic_dialogs.py", line 240, in on_okButton
    if ipmag.combine_magic(files, 'magic_measurements.txt'):
  File "/Users/ltauxe/Programs/PmagPy/GIT/PmagPy/pmagpy/ipmag.py", line 1612, in combine_magic
    pmag.magic_write(outfile,Recs,file_type)
  File "/Users/ltauxe/Programs/PmagPy/GIT/PmagPy/pmagpy/pmag.py", line 1422, in magic_write
    os.mkdir(os.path.split(ofile)[0])
OSError: [Errno 2] No such file or directory: ''
File  /Users/ltauxe/Dropbox/4Christeanne/Aged_Thellier_III/FreshTRM_III.mag.magic  read in with  1126  records
1126  records written to file  magic_measurements.txt
Traceback (most recent call last):
  File "/Users/ltauxe/Programs/PmagPy/GIT/PmagPy/dialogs/pmag_basic_dialogs.py", line 240, in on_okButton
    if ipmag.combine_magic(files, 'magic_measurements.txt'):
  File "/Users/ltauxe/Programs/PmagPy/GIT/PmagPy/pmagpy/ipmag.py", line 1612, in combine_magic
    pmag.magic_write(outfile,Recs,file_type)
  File "/Users/ltauxe/Programs/PmagPy/GIT/PmagPy/pmagpy/pmag.py", line 1422, in magic_write
    os.mkdir(os.path.split(ofile)[0])
OSError: [Errno 2] No such file or directory: ''

Is this because I'm in a Dropbox folder?

**Comment by Caoimhinmg** [comment]
Hey @ltauxe, I went ahead and patched this because I think that's actually a line of code in magic_write which is causing the problem and I managed to quickly recreate the problem on my computer. I added a check that fixed it over here. Let me know if you still have the bug by reopening the github issue.
